//===-- MSPUSubtarget.h - Define Subtarget for the MSPU -------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the MSPU specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef MSPU_SUBTARGET_H
#define MSPU_SUBTARGET_H

#include "llvm/Target/TargetSubtargetInfo.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "MSPUGenSubtargetInfo.inc"

namespace llvm
{
	class StringRef;

	class MSPUSubtarget: public MSPUGenSubtargetInfo
	{
			InstrItineraryData InstrItins;
		public:
			MSPUSubtarget(const std::string &TT,
							const std::string &CPU,
							const std::string &FS);

			/// ParseSubtargetFeatures - Parses features string setting specified
			/// subtarget options.  Definition of function is auto generated by tblgen.
			void
			ParseSubtargetFeatures(StringRef CPU, StringRef FS);

			/// getInstrItins - Return the instruction itineraies based on subtarget
			/// selection.
			const InstrItineraryData &
			getInstrItineraryData() const { return InstrItins; }
	};
}  // end namespace llvm

#endif
