#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += ape.o loader.o lib_init.o db_lexer.ragel.o db_parser.bison.o
obj-y += vlog_lexer.ragel.o vlog_parser.bison.o

