//===-- MMPULiteSubtarget.h - Define Subtarget for the MMPULite -------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the MMPULite specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef MMPULITE_SUBTARGET_H
#define MMPULITE_SUBTARGET_H

#include "llvm/Target/TargetSubtargetInfo.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "MMPULiteGenSubtargetInfo.inc"

namespace llvm
{
	class StringRef;

	class MMPULiteSubtarget: public MMPULiteGenSubtargetInfo
	{
			InstrItineraryData InstrItins;
		public:
			MMPULiteSubtarget(const std::string &TT,
							const std::string &CPU,
							const std::string &FS);

			/// ParseSubtargetFeatures - Parses features string setting specified
			/// subtarget options.  Definition of function is auto generated by tblgen.
			void
			ParseSubtargetFeatures(StringRef CPU, StringRef FS);

			std::string
			getDataLayout() const
			{
				const char *p;
				// Attention: p:?:?:? will change the data type of frame index.
				// isize:abi-align:pref-align
				p = "e-p:64:32:32-i8:8:8-i16:16:16-i32:32:32-f32:32:32-f64:32:32-n8:16:32-S32-a0:8:8-s0:32:32";
				return std::string(p);
			}

			/// getInstrItins - Return the instruction itineraies based on subtarget
			/// selection.
			const InstrItineraryData &
			getInstrItineraryData() const { return InstrItins; }
	};
}  // end namespace llvm

#endif
