/*
 * irqs.h
 *
 *  Created on: Nov 17, 2014
 *      Author: wangl
 */

#ifndef __MACH_IRQS_PBA8_H
#define __MACH_IRQS_PBA8_H

#define IRQ_A8_GIC_START      32

enum SOC_INTR_TABLE {
  INTR_GMAC = IRQ_A8_GIC_START,
  INTR_RTC,
  INTR_UART0,
  INTR_UART1,
  INTR_DMACTRL,
  INTR_DDRCTRL,
  INTR_SPI0,
  INTR_SPI1,
  INTR_TIMERS = IRQ_A8_GIC_START + 8,
  INTR_GPIO = IRQ_A8_GIC_START + 15,
  INTR_I2C0 = IRQ_A8_GIC_START + 24,
  INTR_I2C1,
  INTR_I2C2,
  INTR_I2C3,
  INTR_I2S0,
  INTR_I2S1,
  INTR_WATCHDOG,
  INTR_SDC,
  INTR_DMAEXTERR,
  INTR_DMA,
  INTR_DMAS,
  INTR_PMU,
  INTR_CAMERA,
  INTR_DISPLAY,
  INTR_DDR0CTRL,
  INTR_DDR1CTRL,
  INTR_RIO0,
  INTR_RIO1,
  INTR_APE0,
  INTR_APE0MAIL,
  INTR_APE1,
  INTR_APE1MAIL,
  INTR_APE2,
  INTR_APE2MAIL,
  INTR_APE3,
  INTR_APE3MAIL,
  INTR_PMT,
  INTR_ARMCTI,
  INTR_PCIE0,
  INTR_PCIE1,
  INTR_CODA,
  INTR_JPEG,
  NUM_INTR = IRQ_A8_GIC_START + 128,
};

#define NR_GIC   1

#define NR_IRQS_PBA8    (IRQ_PBA8_GIC_START + 64)
#if !defined(NR_IRQS) || (NR_IRQS < NUM_INTR)
#undef NR_IRQS
#define NR_IRQS     NUM_INTR
#endif

#if !defined(MAX_GIC_NR) || (MAX_GIC_NR < NR_GIC)
#undef MAX_GIC_NR
#define MAX_GIC_NR    NR_GIC
#endif

#endif /* __MACH_IRQS_PBA8_H */
