#! /usr/bin/python
# -*- coding: utf-8 -*-
from PyQt4.QtGui import *
from PyQt4.QtCore import *

import res.qrc_resources

QTextCodec.setCodecForTr(QTextCodec.codecForName("utf8"))

class MainWindow(QMainWindow):
    def __init__(self, parent = None):
        super(MainWindow, self).__init__(parent)
        self.setWindowTitle("MaPU Simulator")
        self.createActions()
        self.createMenus()
        self.createToolBars()

    def createActions(self):
        self.fileOpenAction = QAction(QIcon(":/fileopen.png"), self.tr("打开"), self)
        self.fileNewAction = QAction(QIcon(":/filenew.png"), self.tr("新建"), self)
        self.fileSaveAction = QAction(QIcon(":/filesave.png"), self.tr("保存"), self)
        self.exitAction = QAction(QIcon(":/filequit.png"), self.tr("退出"), self)
        self.cutAction = QAction(QIcon(":/editcut.png"), self.tr("剪切"), self)
        self.copyAction = QAction(QIcon(":/editcopy.png"), self.tr("复制"), self)
        self.pasteAction = QAction(QIcon(":/editpaste.png"), self.tr("粘贴"), self)
        self.aboutAction = QAction(self.tr("关于"), self)

    def createMenus(self):
        fileMenu=self.menuBar().addMenu(self.tr("文件"))
        editMenu=self.menuBar().addMenu(self.tr("编辑"))
        aboutMenu=self.menuBar().addMenu(self.tr("帮助"))

    def createToolBars(self):
        fileToolBar=self.addToolBar("File")
        fileToolBar.addAction(self.fileNewAction)
        fileToolBar.addAction(self.fileOpenAction)
        fileToolBar.addAction(self.fileSaveAction)
        editTool=self.addToolBar("Edit")
        editTool.addAction(self.copyAction)
        editTool.addAction(self.cutAction)
        editTool.addAction(self.pasteAction)
        self.setWindowTitle('MaPU Simulator')
        self.statusBar().showMessage(self.tr("状态栏"))
        tab1=QDialog()
        self.tab2=QDialog()
        self.tab3=QDialog()
        tab4=QDialog()
        tabwidge=QTabWidget()
        tabwidge.addTab(tab1,self.tr("模拟器信息"))
        tabwidge.addTab(self.tab2,self.tr("ARM视窗"))
        tabwidge.addTab(self.tab3,self.tr("APC视窗"))
        tabwidge.addTab(tab4,self.tr("配置与控制"))
        self.setCentralWidget(tabwidge)
        
        tab1.label1=QLabel("SoC")
        tab1.label2=QLabel("ARM")
        tab1.label3=QLabel("APC")
        tab1.button1=QPushButton(self.tr("刷新"))
        tab1.button2=QPushButton(self.tr("刷新"))
        tab1.button3=QPushButton(self.tr("刷新"))
        self.text1=QTextEdit()
        self.text2=QTextEdit()
        self.text3=QTextEdit()
        tab1.layout1=QHBoxLayout()
        tab1.layout1.setMargin(15)
        tab1.layout1.addWidget(tab1.label1)
        tab1.layout1.addWidget(tab1.button1)
        tab1.layout1.addWidget(tab1.label2)
        tab1.layout1.addWidget(tab1.button2)
        tab1.layout1.addWidget(tab1.label3)
        tab1.layout1.addWidget(tab1.button3)
        tab1.layout2=QHBoxLayout()
        tab1.layout2.addWidget(self.text1)
        tab1.layout2.addWidget(self.text2)
        tab1.layout2.addWidget(self.text3)
        tab1.mainLayout=QVBoxLayout()
        tab1.mainLayout.setSpacing(10)
        tab1.mainLayout.addLayout(tab1.layout1)
        tab1.mainLayout.addLayout(tab1.layout2)
        tab1.setLayout(tab1.mainLayout)
        self.connect(tab1.button1,SIGNAL("clicked()"),self.slotClear1)
        self.connect(tab1.button2,SIGNAL("clicked()"),self.slotClear2)
        self.connect(tab1.button3,SIGNAL("clicked()"),self.slotClear3)
        
        self.tab3.Ltabapc=QDialog()  # the detail of APC
        self.tab3.Lape0=QTabWidget()
        self.tab3.Lape1=QDialog()
        self.tab3.Lape2=QDialog()
        self.tab3.Lape3=QDialog()      
        self.tab3.Ltab=QTabWidget()
        self.tab3.Ltab.addTab(self.tab3.Ltabapc,"APC")
        self.tab3.Ltab.addTab(self.tab3.Lape0,"APE0")         
        self.tab3.Ltab.addTab(self.tab3.Lape1,"APE1")
        self.tab3.Ltab.addTab(self.tab3.Lape2,"APE2")
        self.tab3.Ltab.addTab(self.tab3.Lape3,"APE3")   
                       
        self.tab3.Lape0.Spubut=QDialog()
        self.tab3.Lape0.Mpubut=QDialog()
        self.tab3.Lape0.setTabPosition(QTabWidget.South)
        self.tab3.Lape0.addTab(self.tab3.Lape0.Spubut,'SPU')
        self.tab3.Lape0.addTab(self.tab3.Lape0.Mpubut,'MPU')

        self.tab3.Lape0.Mpubut.biu=QTableWidget()
        self.tab3.Lape0.Mpubut.biu.setColumnCount(1)  
        self.tab3.Lape0.Mpubut.biu.setRowCount(4) 
        biu1 = QTableWidgetItem(self.tr("BIUO流水线 "))          
        biu1.setTextColor(QColor(200,111,100))  
        biu1.setFont(QFont("Helvetica"))  
        self.tab3.Lape0.Mpubut.biu.setItem(0,0,biu1)       
        self.tab3.Lape0.Mpubut.biu.setItem(1,0,QTableWidgetItem("sn:41,sin:3"))
        self.tab3.Lape0.Mpubut.biu.setItem(2,0,QTableWidgetItem("sn:55,sin:4"))
        self.tab3.Lape0.Mpubut.biu.setItem(3,0,QTableWidgetItem("sn:69,sin:5"))
         
        Byte=QComboBox()  
        Byte.insertItem(0,'1 Bytes')  
        Byte.insertItem(1,'2 Bytes') 
        Byte.insertItem(2,'3 Bytes')
        Byte.insertItem(3,'4 Bytes')

        Lane=QComboBox()  
        Lane.insertItem(0,'Lane0')  
        Lane.insertItem(1,'Lane1')
        Lane.insertItem(2,'Lane2')
        Lane.insertItem(3,'Lane3')
       
        self.tab3.Lape0.Mpubut.uplayoul=QHBoxLayout()        
        #self.tab3.Lape0.Mpubut.uplayoul.addWidget(self.tab3.Lape0.Mpubut.biu)
        self.tab3.Lape0.Mpubut.uplayoul.addStretch()  
        self.tab3.Lape0.Mpubut.uplayoul.addWidget(Byte)
        self.tab3.Lape0.Mpubut.uplayoul.addWidget(Lane)
 
        BIU0=QPushButton()
        BIU1=QPushButton()
        BIU2=QPushButton()
        SHU0=QPushButton()
        SHU0.resize(20,15)
        Shu0toMrf=QLineEdit()  
        MRF=QPushButton()
        MrftoShu1=QLineEdit() 
        SHU1=QPushButton()
        IALU=QPushButton()
        IMAC=QPushButton()
        FALU=QPushButton()
        FMAC=QPushButton()
        
        self.tab3.Lape0.Mpubut.downlayoul=QGridLayout()
        self.tab3.Lape0.Mpubut.downlayoul.setSpacing(50)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(self.tab3.Lape0.Mpubut.biu,0,0,2,1)
        #self.tab3.Lape0.Mpubut.downlayoul.addWidget(,1,0)
        #self.tab3.Lape0.Mpubut.downlayoul.addStretch() 
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(BIU0,2,0)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(BIU1,3,0)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(BIU2,4,0)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(SHU0,0,1) 
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(Shu0toMrf,1,1)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(MRF,2,1)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(MrftoShu1,3,1)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(SHU1,4,1)
        #self.tab3.Lape0.Mpubut.downlayoul.addWidget(0,2)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(IALU,1,2)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(IMAC,2,2)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(FALU,3,2)
        self.tab3.Lape0.Mpubut.downlayoul.addWidget(FMAC,4,2) 
       
        self.tab3.Lape0.Mpubut.alllayoul=QVBoxLayout()
        self.tab3.Lape0.Mpubut.alllayoul.addLayout(self.tab3.Lape0.Mpubut.uplayoul) 
        self.tab3.Lape0.Mpubut.alllayoul.addLayout(self.tab3.Lape0.Mpubut.downlayoul)  
        self.tab3.Lape0.Mpubut.alllayoul.setAlignment(Qt.AlignCenter)
        self.tab3.Lape0.Mpubut.setLayout(self.tab3.Lape0.Mpubut.alllayoul)              
    
        


          
        butt0=QPushButton("APE0")   
        butt1=QPushButton("APE1")        
        butt2=QPushButton("APE2")
        butt3=QPushButton("APE3")
        self.tab3.Ltabapc.apclayout=QGridLayout()
        self.tab3.Ltabapc.apclayout.setMargin(70)  
        self.tab3.Ltabapc.apclayout.setSpacing(50)  
        self.tab3.Ltabapc.apclayout.addWidget(butt0,0,0)          
        self.tab3.Ltabapc.apclayout.addWidget(butt3,0,1) 
        self.tab3.Ltabapc.apclayout.addWidget(butt1,1,0) 
        self.tab3.Ltabapc.apclayout.addWidget(butt2,1,1) 
        self.tab3.Ltabapc.apclayout.setAlignment(Qt.AlignCenter)
        self.tab3.Ltabapc.setLayout(self.tab3.Ltabapc.apclayout)
        self.tab3.connect(butt0,SIGNAL("clicked()"),self.slottab0)
        self.tab3.connect(butt1,SIGNAL("clicked()"),self.slottab1)
        self.tab3.connect(butt2,SIGNAL("clicked()"),self.slottab2)
        self.tab3.connect(butt3,SIGNAL("clicked()"),self.slottab3)                                    
 
        wDMA=QTableWidget()   
        nDMA=QTableWidget()
        station=QDialog()

        Sregister=QTableWidget()
        Spccialreg=QTableWidget()
        Strace=QTableWidget()

        Mregister=QTableWidget()
        Mpccialreg=QTableWidget()
        Mtrace=QTableWidget()
       
        self.tab3.Rtab=QTabWidget() 
        self.tab3.Rtab.addTab(wDMA,self.tr("外DMA"))
        self.tab3.Rtab.addTab(nDMA,self.tr("内DMA"))
        self.tab3.Rtab.addTab(station,self.tr("状态"))
        self.tab3.Rtab.addTab(Sregister,self.tr("寄存器堆"))
        self.tab3.Rtab.addTab(Spccialreg,self.tr("特殊Reg"))
        self.tab3.Rtab.addTab(Strace,self.tr("Trace"))
        self.tab3.Rtab.addTab(Mregister,self.tr("寄存器堆"))
        self.tab3.Rtab.addTab(Mpccialreg,self.tr("特殊Reg"))
        self.tab3.Rtab.addTab(Mtrace,self.tr("Trace"))
       
        wDMA.setColumnCount(2)  
        wDMA.setRowCount(10)  
        witem0 = QTableWidgetItem(self.tr("通道0"))          
        witem0.setTextColor(QColor(200,111,100))  
        witem0.setFont(QFont("Helvetica"))         
        witem1 = QTableWidgetItem(self.tr("通道1"))          
        witem1.setTextColor(QColor(200,111,100))  
        witem1.setFont(QFont("Helvetica"))         
        wDMA.setItem(0,0,witem0)        
        wDMA.setItem(1,0,QTableWidgetItem(self.tr("目标地址")))
        wDMA.setItem(2,0,QTableWidgetItem(self.tr("源地址")))
        wDMA.setItem(3,0,QTableWidgetItem(self.tr("X长度")))
        wDMA.setItem(4,0,QTableWidgetItem(self.tr("Y长度")))
        wDMA.setItem(5,0,witem1)
        wDMA.setItem(6,0,QTableWidgetItem(self.tr("目标地址")))
        wDMA.setItem(7,0,QTableWidgetItem(self.tr("源地址")))
        wDMA.setItem(8,0,QTableWidgetItem(self.tr("X长度")))
        wDMA.setItem(9,0,QTableWidgetItem(self.tr("Y长度")))
  
        nDMA.setColumnCount(2)  
        nDMA.setRowCount(10)  
        nitem0 = QTableWidgetItem(self.tr("通道0"))          
        nitem0.setTextColor(QColor(200,111,100))  
        nitem0.setFont(QFont("Helvetica"))         
        nitem1 = QTableWidgetItem(self.tr("通道1"))          
        nitem1.setTextColor(QColor(200,111,100))  
        nitem1.setFont(QFont("Helvetica"))       
        nDMA.setItem(0,0,nitem0)       
        nDMA.setItem(1,0,QTableWidgetItem(self.tr("目标地址")))
        nDMA.setItem(2,0,QTableWidgetItem(self.tr("源地址")))
        nDMA.setItem(3,0,QTableWidgetItem(self.tr("X长度")))
        nDMA.setItem(4,0,QTableWidgetItem(self.tr("Y长度")))
        nDMA.setItem(5,0,nitem1)        
        nDMA.setItem(6,0,QTableWidgetItem(self.tr("目标地址")))
        nDMA.setItem(7,0,QTableWidgetItem(self.tr("源地址")))
        nDMA.setItem(8,0,QTableWidgetItem(self.tr("X长度")))
        nDMA.setItem(9,0,QTableWidgetItem(self.tr("Y长度")))
              
        Sregister.setColumnCount(2)  
        Sregister.setRowCount(10)  
        Sitem0 = QTableWidgetItem('R')          
        Sitem0.setTextColor(QColor(200,111,100))  
        Sitem0.setFont(QFont("Helvetica"))         
        Sitem1 = QTableWidgetItem('J')          
        Sitem1.setTextColor(QColor(200,111,100))  
        Sitem1.setFont(QFont("Helvetica"))       
        Sregister.setItem(0,0,Sitem0)       
        Sregister.setItem(1,0,QTableWidgetItem('R0'))
        Sregister.setItem(2,0,QTableWidgetItem('R1'))
        Sregister.setItem(3,0,QTableWidgetItem('R2'))
        Sregister.setItem(4,0,QTableWidgetItem('R3'))
        Sregister.setItem(5,0,Sitem1)        
        Sregister.setItem(6,0,QTableWidgetItem('J0'))
        Sregister.setItem(7,0,QTableWidgetItem('J1'))
        Sregister.setItem(8,0,QTableWidgetItem('FP'))
        Sregister.setItem(9,0,QTableWidgetItem('SP'))

        Mregister.setColumnCount(2)  
        Mregister.setRowCount(10)  
        Mitem0 = QTableWidgetItem('M')          
        Mitem0.setTextColor(QColor(200,111,100))  
        Mitem0.setFont(QFont("Helvetica"))         
        Mitem1 = QTableWidgetItem('SHUO T')          
        Mitem1.setTextColor(QColor(200,111,100))  
        Mitem1.setFont(QFont("Helvetica"))       
        Mregister.setItem(0,0,Mitem0)       
        Mregister.setItem(1,0,QTableWidgetItem('M0'))
        Mregister.setItem(2,0,QTableWidgetItem('M1'))
        Mregister.setItem(3,0,QTableWidgetItem('M2'))
        Mregister.setItem(4,0,QTableWidgetItem('M3'))
        Mregister.setItem(5,0,Mitem1)        
        Mregister.setItem(6,0,QTableWidgetItem('T0'))
        Mregister.setItem(7,0,QTableWidgetItem('T1'))
        Mregister.setItem(8,0,QTableWidgetItem('T2'))
        Mregister.setItem(9,0,QTableWidgetItem('T3'))
            
        self.tab3.hlayout=QHBoxLayout()  
        self.tab3.hlayout.addWidget(self.tab3.Ltab)  
        self.tab3.hlayout.addWidget(self.tab3.Rtab) 
        self.tab3.hlayout.setStretchFactor(self.tab3.Ltab,2)  
        self.tab3.hlayout.setStretchFactor(self.tab3.Rtab,1)          
        
        self.tab3.slider = QSlider(Qt.Horizontal)
        self.tab3.slider.setTickPosition(QSlider.TicksBothSides)
        self.tab3.slider.setMinimum(0)
        self.tab3.slider.setMaximum(100)  
        self.tab3.slider.setValue(50)          
        self.tab3.mainLayout=QVBoxLayout()
        self.tab3.mainLayout.addLayout(self.tab3.hlayout)
        self.tab3.mainLayout.addWidget(self.tab3.slider)
        self.tab3.setLayout(self.tab3.mainLayout)   
         
        self.tab2.Uart0=QDialog()    #the detail of ARM
        self.tab2.Uart1=QDialog()
        self.tab2.Lcd=QDialog()
        self.tab2.uptabwidget=QTabWidget() 
        self.tab2.uptabwidget.addTab(self.tab2.Uart0,"UART0")
        self.tab2.uptabwidget.addTab(self.tab2.Uart1,"UART1")
        self.tab2.uptabwidget.addTab(self.tab2.Lcd,"LCD")        
        self.tab2.text=QTextEdit()
        self.tab2.text.setWordWrapMode(QTextOption.NoWrap)               
        self.tab2.Gdbbutt=QPushButton("GDB")
        self.tab2.Console=QPushButton("Console")
        self.tab2.bottom=QHBoxLayout()                 
        self.tab2.bottom.addWidget(self.tab2.Gdbbutt)
        self.tab2.bottom.addWidget(self.tab2.Console)
        self.tab2.bottom.addStretch()  
        self.tab2.vlayout=QVBoxLayout()
        self.tab2.vlayout.addWidget(self.tab2.uptabwidget)     
        self.tab2.vlayout.addWidget(self.tab2.text)
        self.tab2.vlayout.addLayout(self.tab2.bottom)
        self.tab2.setLayout(self.tab2.vlayout)     
    def slotClear1(self):
        self.text1.clear()

    def slotClear2(self):
        self.text2.clear()

    def slotClear3(self):
        self.text3.clear()

    def slottab0(self):
        self.tab3.Ltab.setCurrentWidget(self.tab3.Lape0)  

    def slottab1(self):
        self.tab3.Ltab.setCurrentWidget(self.tab3.Lape1) 

    def slottab2(self):
        self.tab3.Ltab.setCurrentWidget(self.tab3.Lape2) 

    def slottab3(self):
        self.tab3.Ltab.setCurrentWidget(self.tab3.Lape3)










