#ifndef DDR_CTRL_H
#define DDR_CTRL_H
#define ADDITIVE_LAT_ADDR              5                    
#define ADDITIVE_LAT_OFFSET            16                   
#define ADDITIVE_LAT_WIDTH             5                    
#define ADDRESS_MIRRORING_ADDR         12                   
#define ADDRESS_MIRRORING_OFFSET       24                   
#define ADDRESS_MIRRORING_WIDTH        2                    
#define ADDR_CMP_EN_ADDR               42                   
#define ADDR_CMP_EN_OFFSET             0                    
#define ADDR_CMP_EN_WIDTH              1                    
#define ADDR_COLLISION_MPM_DIS_ADDR    160                  
#define ADDR_COLLISION_MPM_DIS_OFFSET  0                    
#define ADDR_COLLISION_MPM_DIS_WIDTH   1                    
#define ADDR_SPACE_ADDR                30                   
#define ADDR_SPACE_OFFSET              0                    
#define ADDR_SPACE_WIDTH               6                    
#define ADD_ODT_CLK_DIFFTYPE_DIFFCS_ADDR 75                   
#define ADD_ODT_CLK_DIFFTYPE_DIFFCS_OFFSET 16                   
#define ADD_ODT_CLK_DIFFTYPE_DIFFCS_WIDTH 6                    
#define ADD_ODT_CLK_R2W_SAMECS_ADDR    75                   
#define ADD_ODT_CLK_R2W_SAMECS_OFFSET  0                    
#define ADD_ODT_CLK_R2W_SAMECS_WIDTH   4                    
#define ADD_ODT_CLK_SAMETYPE_DIFFCS_ADDR 75                   
#define ADD_ODT_CLK_SAMETYPE_DIFFCS_OFFSET 24                   
#define ADD_ODT_CLK_SAMETYPE_DIFFCS_WIDTH 4                    
#define ADD_ODT_CLK_W2R_SAMECS_ADDR    75                   
#define ADD_ODT_CLK_W2R_SAMECS_OFFSET  8                    
#define ADD_ODT_CLK_W2R_SAMECS_WIDTH   4                    
#define AGE_COUNT_ADDR                 41                   
#define AGE_COUNT_OFFSET               16                   
#define AGE_COUNT_WIDTH                8                    
#define AP_ADDR                        11                   
#define AP_OFFSET                      0                    
#define AP_WIDTH                       1                    
#define APREBIT_ADDR                   41                   
#define APREBIT_OFFSET                 8                    
#define APREBIT_WIDTH                  4                    
#define ARB_CMD_Q_THRESHOLD_ADDR       122                  
#define ARB_CMD_Q_THRESHOLD_OFFSET     0                    
#define ARB_CMD_Q_THRESHOLD_WIDTH      4                    
#define AREFRESH_ADDR                  13                   
#define AREFRESH_OFFSET                0                    
#define AREFRESH_WIDTH                 1                    
#define ASYNC_CDC_STAGES_ADDR          152                  
#define ASYNC_CDC_STAGES_OFFSET        24                   
#define ASYNC_CDC_STAGES_WIDTH         8                    
#define AUTO_REFRESH_MODE_ADDR         13                   
#define AUTO_REFRESH_MODE_OFFSET       8                    
#define AUTO_REFRESH_MODE_WIDTH        1                    
#define AXI0_BDW_ADDR                  122                  
#define AXI0_BDW_OFFSET                8                    
#define AXI0_BDW_WIDTH                 7                    
#define AXI0_BDW_OVFLOW_ADDR           122                  
#define AXI0_BDW_OVFLOW_OFFSET         16                   
#define AXI0_BDW_OVFLOW_WIDTH          1                    
#define AXI0_CMDFIFO_LOG2_DEPTH_ADDR   153                  
#define AXI0_CMDFIFO_LOG2_DEPTH_OFFSET 0                    
#define AXI0_CMDFIFO_LOG2_DEPTH_WIDTH  8                    
#define AXI0_CURRENT_BDW_ADDR          122                  
#define AXI0_CURRENT_BDW_OFFSET        24                   
#define AXI0_CURRENT_BDW_WIDTH         7                    
#define AXI0_FIFO_TYPE_REG_ADDR        119                  
#define AXI0_FIFO_TYPE_REG_OFFSET      16                   
#define AXI0_FIFO_TYPE_REG_WIDTH       2                    
#define AXI0_RDFIFO_LOG2_DEPTH_ADDR    153                  
#define AXI0_RDFIFO_LOG2_DEPTH_OFFSET  8                    
#define AXI0_RDFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI0_R_PRIORITY_ADDR           119                  
#define AXI0_R_PRIORITY_OFFSET         0                    
#define AXI0_R_PRIORITY_WIDTH          3                    
#define AXI0_TRANS_WRFIFO_LOG2_DEPTH_ADDR 153                  
#define AXI0_TRANS_WRFIFO_LOG2_DEPTH_OFFSET 24                   
#define AXI0_TRANS_WRFIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI0_WRCMD_PROC_FIFO_LOG2_DEPTH_ADDR 154                  
#define AXI0_WRCMD_PROC_FIFO_LOG2_DEPTH_OFFSET 0                    
#define AXI0_WRCMD_PROC_FIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI0_WRFIFO_LOG2_DEPTH_ADDR    153                  
#define AXI0_WRFIFO_LOG2_DEPTH_OFFSET  16                   
#define AXI0_WRFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI0_W_PRIORITY_ADDR           119                  
#define AXI0_W_PRIORITY_OFFSET         8                    
#define AXI0_W_PRIORITY_WIDTH          3                    
#define AXI1_BDW_ADDR                  123                  
#define AXI1_BDW_OFFSET                0                    
#define AXI1_BDW_WIDTH                 7                    
#define AXI1_BDW_OVFLOW_ADDR           123                  
#define AXI1_BDW_OVFLOW_OFFSET         8                    
#define AXI1_BDW_OVFLOW_WIDTH          1                    
#define AXI1_CMDFIFO_LOG2_DEPTH_ADDR   154                  
#define AXI1_CMDFIFO_LOG2_DEPTH_OFFSET 8                    
#define AXI1_CMDFIFO_LOG2_DEPTH_WIDTH  8                    
#define AXI1_CURRENT_BDW_ADDR          123                  
#define AXI1_CURRENT_BDW_OFFSET        16                   
#define AXI1_CURRENT_BDW_WIDTH         7                    
#define AXI1_FIFO_TYPE_REG_ADDR        120                  
#define AXI1_FIFO_TYPE_REG_OFFSET      8                    
#define AXI1_FIFO_TYPE_REG_WIDTH       2                    
#define AXI1_RDFIFO_LOG2_DEPTH_ADDR    154                  
#define AXI1_RDFIFO_LOG2_DEPTH_OFFSET  16                   
#define AXI1_RDFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI1_R_PRIORITY_ADDR           119                  
#define AXI1_R_PRIORITY_OFFSET         24                   
#define AXI1_R_PRIORITY_WIDTH          3                    
#define AXI1_TRANS_WRFIFO_LOG2_DEPTH_ADDR 155                  
#define AXI1_TRANS_WRFIFO_LOG2_DEPTH_OFFSET 0                    
#define AXI1_TRANS_WRFIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI1_WRCMD_PROC_FIFO_LOG2_DEPTH_ADDR 155                  
#define AXI1_WRCMD_PROC_FIFO_LOG2_DEPTH_OFFSET 8                    
#define AXI1_WRCMD_PROC_FIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI1_WRFIFO_LOG2_DEPTH_ADDR    154                  
#define AXI1_WRFIFO_LOG2_DEPTH_OFFSET  24                   
#define AXI1_WRFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI1_W_PRIORITY_ADDR           120                  
#define AXI1_W_PRIORITY_OFFSET         0                    
#define AXI1_W_PRIORITY_WIDTH          3                    
#define AXI2_BDW_ADDR                  123                  
#define AXI2_BDW_OFFSET                24                   
#define AXI2_BDW_WIDTH                 7                    
#define AXI2_BDW_OVFLOW_ADDR           124                  
#define AXI2_BDW_OVFLOW_OFFSET         0                    
#define AXI2_BDW_OVFLOW_WIDTH          1                    
#define AXI2_CMDFIFO_LOG2_DEPTH_ADDR   155                  
#define AXI2_CMDFIFO_LOG2_DEPTH_OFFSET 16                   
#define AXI2_CMDFIFO_LOG2_DEPTH_WIDTH  8                    
#define AXI2_CURRENT_BDW_ADDR          124                  
#define AXI2_CURRENT_BDW_OFFSET        8                    
#define AXI2_CURRENT_BDW_WIDTH         7                    
#define AXI2_FIFO_TYPE_REG_ADDR        121                  
#define AXI2_FIFO_TYPE_REG_OFFSET      0                    
#define AXI2_FIFO_TYPE_REG_WIDTH       2                    
#define AXI2_RDFIFO_LOG2_DEPTH_ADDR    155                  
#define AXI2_RDFIFO_LOG2_DEPTH_OFFSET  24                   
#define AXI2_RDFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI2_R_PRIORITY_ADDR           120                  
#define AXI2_R_PRIORITY_OFFSET         16                   
#define AXI2_R_PRIORITY_WIDTH          3                    
#define AXI2_TRANS_WRFIFO_LOG2_DEPTH_ADDR 156                  
#define AXI2_TRANS_WRFIFO_LOG2_DEPTH_OFFSET 8                    
#define AXI2_TRANS_WRFIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI2_WRCMD_PROC_FIFO_LOG2_DEPTH_ADDR 156                  
#define AXI2_WRCMD_PROC_FIFO_LOG2_DEPTH_OFFSET 16                   
#define AXI2_WRCMD_PROC_FIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI2_WRFIFO_LOG2_DEPTH_ADDR    156                  
#define AXI2_WRFIFO_LOG2_DEPTH_OFFSET  0                    
#define AXI2_WRFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI2_W_PRIORITY_ADDR           120                  
#define AXI2_W_PRIORITY_OFFSET         24                   
#define AXI2_W_PRIORITY_WIDTH          3                    
#define AXI3_BDW_ADDR                  124                  
#define AXI3_BDW_OFFSET                16                   
#define AXI3_BDW_WIDTH                 7                    
#define AXI3_BDW_OVFLOW_ADDR           124                  
#define AXI3_BDW_OVFLOW_OFFSET         24                   
#define AXI3_BDW_OVFLOW_WIDTH          1                    
#define AXI3_CMDFIFO_LOG2_DEPTH_ADDR   156                  
#define AXI3_CMDFIFO_LOG2_DEPTH_OFFSET 24                   
#define AXI3_CMDFIFO_LOG2_DEPTH_WIDTH  8                    
#define AXI3_CURRENT_BDW_ADDR          125                  
#define AXI3_CURRENT_BDW_OFFSET        0                    
#define AXI3_CURRENT_BDW_WIDTH         7                    
#define AXI3_FIFO_TYPE_REG_ADDR        121                  
#define AXI3_FIFO_TYPE_REG_OFFSET      24                   
#define AXI3_FIFO_TYPE_REG_WIDTH       2                    
#define AXI3_RDFIFO_LOG2_DEPTH_ADDR    157                  
#define AXI3_RDFIFO_LOG2_DEPTH_OFFSET  0                    
#define AXI3_RDFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI3_R_PRIORITY_ADDR           121                  
#define AXI3_R_PRIORITY_OFFSET         8                    
#define AXI3_R_PRIORITY_WIDTH          3                    
#define AXI3_TRANS_WRFIFO_LOG2_DEPTH_ADDR 157                  
#define AXI3_TRANS_WRFIFO_LOG2_DEPTH_OFFSET 16                   
#define AXI3_TRANS_WRFIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI3_WRCMD_PROC_FIFO_LOG2_DEPTH_ADDR 157                  
#define AXI3_WRCMD_PROC_FIFO_LOG2_DEPTH_OFFSET 24                   
#define AXI3_WRCMD_PROC_FIFO_LOG2_DEPTH_WIDTH 8                    
#define AXI3_WRFIFO_LOG2_DEPTH_ADDR    157                  
#define AXI3_WRFIFO_LOG2_DEPTH_OFFSET  8                    
#define AXI3_WRFIFO_LOG2_DEPTH_WIDTH   8                    
#define AXI3_W_PRIORITY_ADDR           121                  
#define AXI3_W_PRIORITY_OFFSET         16                   
#define AXI3_W_PRIORITY_WIDTH          3                    
#define BANK_DIFF_ADDR                 40                   
#define BANK_DIFF_OFFSET               16                   
#define BANK_DIFF_WIDTH                2                    
#define BANK_SPLIT_EN_ADDR             42                   
#define BANK_SPLIT_EN_OFFSET           8                    
#define BANK_SPLIT_EN_WIDTH            1                    
#define BIST_ADDR_CHECK_ADDR           30                   
#define BIST_ADDR_CHECK_OFFSET         16                   
#define BIST_ADDR_CHECK_WIDTH          1                    
#define BIST_DATA_CHECK_ADDR           30                   
#define BIST_DATA_CHECK_OFFSET         8                    
#define BIST_DATA_CHECK_WIDTH          1                    
#define BIST_DATA_MASK_ADDR            33                   
#define BIST_DATA_MASK_OFFSET          0                    
#define BIST_DATA_MASK_WIDTH           128                  
#define BIST_EXP_DATA_ADDR             53                   
#define BIST_EXP_DATA_OFFSET           0                    
#define BIST_EXP_DATA_WIDTH            256                  
#define BIST_FAIL_ADDR_ADDR            69                   
#define BIST_FAIL_ADDR_OFFSET          0                    
#define BIST_FAIL_ADDR_WIDTH           34                   
#define BIST_FAIL_DATA_ADDR            61                   
#define BIST_FAIL_DATA_OFFSET          0                    
#define BIST_FAIL_DATA_WIDTH           256                  
#define BIST_GO_ADDR                   29                   
#define BIST_GO_OFFSET                 16                   
#define BIST_GO_WIDTH                  1                    
#define BIST_RESULT_ADDR               29                   
#define BIST_RESULT_OFFSET             24                   
#define BIST_RESULT_WIDTH              2                    
#define BIST_START_ADDRESS_ADDR        31                   
#define BIST_START_ADDRESS_OFFSET      0                    
#define BIST_START_ADDRESS_WIDTH       34                   
#define BSTLEN_ADDR                    12                   
#define BSTLEN_OFFSET                  0                    
#define BSTLEN_WIDTH                   3                    
#define BURST_ON_FLY_BIT_ADDR          45                   
#define BURST_ON_FLY_BIT_OFFSET        16                   
#define BURST_ON_FLY_BIT_WIDTH         4                    
#define CASLAT_LIN_ADDR                5                    
#define CASLAT_LIN_OFFSET              0                    
#define CASLAT_LIN_WIDTH               6                    
#define CKE_DELAY_ADDR                 18                   
#define CKE_DELAY_OFFSET               8                    
#define CKE_DELAY_WIDTH                3                    
#define CKE_INACTIVE_ADDR              4                    
#define CKE_INACTIVE_OFFSET            0                    
#define CKE_INACTIVE_WIDTH             32                   
#define CKE_STATUS_ADDR                125                  
#define CKE_STATUS_OFFSET              8                    
#define CKE_STATUS_WIDTH               2                    
#define CKSRE_ADDR                     18                   
#define CKSRE_OFFSET                   24                   
#define CKSRE_WIDTH                    8                    
#define CKSRX_ADDR                     19                   
#define CKSRX_OFFSET                   0                    
#define CKSRX_WIDTH                    8                    
#define COL_DIFF_ADDR                  41                   
#define COL_DIFF_OFFSET                0                    
#define COL_DIFF_WIDTH                 3                    
#define COMMAND_AGE_COUNT_ADDR         41                   
#define COMMAND_AGE_COUNT_OFFSET       24                   
#define COMMAND_AGE_COUNT_WIDTH        8                    
#define CONCURRENTAP_ADDR              11                   
#define CONCURRENTAP_OFFSET            8                    
#define CONCURRENTAP_WIDTH             1                    
#define CONTROLLER_BUSY_ADDR           46                   
#define CONTROLLER_BUSY_OFFSET         16                   
#define CONTROLLER_BUSY_WIDTH          1                    
#define CS_MAP_ADDR                    45                   
#define CS_MAP_OFFSET                  8                    
#define CS_MAP_WIDTH                   2                    
#define CS_SAME_EN_ADDR                43                   
#define CS_SAME_EN_OFFSET              16                   
#define CS_SAME_EN_WIDTH               1                    
#define CTRLUPD_REQ_ADDR               46                   
#define CTRLUPD_REQ_OFFSET             24                   
#define CTRLUPD_REQ_WIDTH              1                    
#define CTRLUPD_REQ_PER_AREF_EN_ADDR   47                   
#define CTRLUPD_REQ_PER_AREF_EN_OFFSET 0                    
#define CTRLUPD_REQ_PER_AREF_EN_WIDTH  1                    
#define DFI_WRLVL_MAX_DELAY_ADDR       137                  
#define DFI_WRLVL_MAX_DELAY_OFFSET     0                    
#define DFI_WRLVL_MAX_DELAY_WIDTH      16                   
#define DISABLE_RD_INTERLEAVE_ADDR     44                   
#define DISABLE_RD_INTERLEAVE_OFFSET   24                   
#define DISABLE_RD_INTERLEAVE_WIDTH    1                    
#define DISABLE_RW_GROUP_W_BNK_CONFLICT_ADDR 44                   
#define DISABLE_RW_GROUP_W_BNK_CONFLICT_OFFSET 0                    
#define DISABLE_RW_GROUP_W_BNK_CONFLICT_WIDTH 2                    
#define DLL_RST_ADJ_DLY_ADDR           126                  
#define DLL_RST_ADJ_DLY_OFFSET         16                   
#define DLL_RST_ADJ_DLY_WIDTH          8                    
#define DLL_RST_DELAY_ADDR             126                  
#define DLL_RST_DELAY_OFFSET           0                    
#define DLL_RST_DELAY_WIDTH            16                   
#define DRAM_CLASS_ADDR                0                    
#define DRAM_CLASS_OFFSET              8                    
#define DRAM_CLASS_WIDTH               4                    
#define DRAM_CLK_DISABLE_ADDR          127                  
#define DRAM_CLK_DISABLE_OFFSET        24                   
#define DRAM_CLK_DISABLE_WIDTH         2                    
#define ENABLE_QUICK_SREFRESH_ADDR     18                   
#define ENABLE_QUICK_SREFRESH_OFFSET   0                    
#define ENABLE_QUICK_SREFRESH_WIDTH    1                    
#define INHIBIT_DRAM_CMD_ADDR          45                   
#define INHIBIT_DRAM_CMD_OFFSET        0                    
#define INHIBIT_DRAM_CMD_WIDTH         1                    
#define INT_ACK_ADDR                   48                   
#define INT_ACK_OFFSET                 0                    
#define INT_ACK_WIDTH                  17                   
#define INT_MASK_ADDR                  49                   
#define INT_MASK_WIDTH                 18                   
#define INT_STATUS_ADDR                47                   
#define INT_STATUS_OFFSET              8                    
#define INT_STATUS_WIDTH               18                   
#define IN_ORDER_ACCEPT_ADDR           46                   
#define IN_ORDER_ACCEPT_OFFSET         8                    
#define IN_ORDER_ACCEPT_WIDTH          1                    
#define LONG_COUNT_MASK_ADDR           158                  
#define LONG_COUNT_MASK_OFFSET         0                    
#define LONG_COUNT_MASK_WIDTH          5                    
#define LOWPOWER_REFRESH_ENABLE_ADDR   18                   
#define LOWPOWER_REFRESH_ENABLE_OFFSET 16                   
#define LOWPOWER_REFRESH_ENABLE_WIDTH  2                    
#define LP_ARB_STATE_ADDR              19                   
#define LP_ARB_STATE_OFFSET            24                   
#define LP_ARB_STATE_WIDTH             4                    
#define LP_AUTO_ENTRY_EN_ADDR          20                   
#define LP_AUTO_ENTRY_EN_OFFSET        0                    
#define LP_AUTO_ENTRY_EN_WIDTH         3                    
#define LP_AUTO_EXIT_EN_ADDR           20                   
#define LP_AUTO_EXIT_EN_OFFSET         8                    
#define LP_AUTO_EXIT_EN_WIDTH          3                    
#define LP_AUTO_MEM_GATE_EN_ADDR       20                   
#define LP_AUTO_MEM_GATE_EN_OFFSET     16                   
#define LP_AUTO_MEM_GATE_EN_WIDTH      2                    
#define LP_AUTO_PD_IDLE_ADDR           21                   
#define LP_AUTO_PD_IDLE_OFFSET         0                    
#define LP_AUTO_PD_IDLE_WIDTH          12                   
#define LP_AUTO_SR_IDLE_ADDR           21                   
#define LP_AUTO_SR_IDLE_OFFSET         16                   
#define LP_AUTO_SR_IDLE_WIDTH          8                    
#define LP_AUTO_SR_MC_GATE_IDLE_ADDR   21                   
#define LP_AUTO_SR_MC_GATE_IDLE_OFFSET 24                   
#define LP_AUTO_SR_MC_GATE_IDLE_WIDTH  8                    
#define LP_CMD_ADDR                    19                   
#define LP_CMD_OFFSET                  8                    
#define LP_CMD_WIDTH                   8                    
#define LP_STATE_ADDR                  19                   
#define LP_STATE_OFFSET                16                   
#define LP_STATE_WIDTH                 6                    
#define LVL_STATUS_ADDR                79                   
#define LVL_STATUS_OFFSET              8                    
#define LVL_STATUS_WIDTH               4                    
#define MAX_COL_REG_ADDR               1                    
#define MAX_COL_REG_OFFSET             8                    
#define MAX_COL_REG_WIDTH              4                    
#define MAX_CS_REG_ADDR                1                    
#define MAX_CS_REG_OFFSET              16                   
#define MAX_CS_REG_WIDTH               2                    
#define MAX_ROW_REG_ADDR               1                    
#define MAX_ROW_REG_OFFSET             0                    
#define MAX_ROW_REG_WIDTH              5                    
#define MEM_RST_VALID_ADDR             125                  
#define MEM_RST_VALID_OFFSET           16                   
#define MEM_RST_VALID_WIDTH            1                    
#define MR0_DATA_0_ADDR                24                   
#define MR0_DATA_0_OFFSET              8                    
#define MR0_DATA_0_WIDTH               16                   
#define MR0_DATA_1_ADDR                27                   
#define MR0_DATA_1_OFFSET              0                    
#define MR0_DATA_1_WIDTH               16                   
#define MR1_DATA_0_ADDR                25                   
#define MR1_DATA_0_OFFSET              0                    
#define MR1_DATA_0_WIDTH               16                   
#define MR1_DATA_1_ADDR                27                   
#define MR1_DATA_1_OFFSET              16                   
#define MR1_DATA_1_WIDTH               16                   
#define MR2_DATA_0_ADDR                25                   
#define MR2_DATA_0_OFFSET              16                   
#define MR2_DATA_0_WIDTH               16                   
#define MR2_DATA_1_ADDR                28                   
#define MR2_DATA_1_OFFSET              0                    
#define MR2_DATA_1_WIDTH               16                   
#define MR3_DATA_0_ADDR                26                   
#define MR3_DATA_0_OFFSET              16                   
#define MR3_DATA_0_WIDTH               16                   
#define MR3_DATA_1_ADDR                29                   
#define MR3_DATA_1_OFFSET              0                    
#define MR3_DATA_1_WIDTH               16                   
#define MRSINGLE_DATA_0_ADDR           26                   
#define MRSINGLE_DATA_0_OFFSET         0                    
#define MRSINGLE_DATA_0_WIDTH          16                   
#define MRSINGLE_DATA_1_ADDR           28                   
#define MRSINGLE_DATA_1_OFFSET         16                   
#define MRSINGLE_DATA_1_WIDTH          16                   
#define MRW_STATUS_ADDR                24                   
#define MRW_STATUS_OFFSET              0                    
#define MRW_STATUS_WIDTH               8                    
#define NUM_Q_ENTRIES_ACT_DISABLE_ADDR 44                   
#define NUM_Q_ENTRIES_ACT_DISABLE_OFFSET 8                    
#define NUM_Q_ENTRIES_ACT_DISABLE_WIDTH 4                    
#define ODT_EN_ADDR                    74                   
#define ODT_EN_OFFSET                  24                   
#define ODT_EN_WIDTH                   1                    
#define ODT_RD_MAP_CS0_ADDR            73                   
#define ODT_RD_MAP_CS0_OFFSET          0                    
#define ODT_RD_MAP_CS0_WIDTH           2                    
#define ODT_RD_MAP_CS1_ADDR            73                   
#define ODT_RD_MAP_CS1_OFFSET          16                   
#define ODT_RD_MAP_CS1_WIDTH           2                    
#define ODT_WR_MAP_CS0_ADDR            73                   
#define ODT_WR_MAP_CS0_OFFSET          8                    
#define ODT_WR_MAP_CS0_WIDTH           2                    
#define ODT_WR_MAP_CS1_ADDR            73                   
#define ODT_WR_MAP_CS1_OFFSET          24                   
#define ODT_WR_MAP_CS1_WIDTH           2                    
#define OUT_OF_RANGE_ADDR_ADDR         50                   
#define OUT_OF_RANGE_ADDR_OFFSET       0                    
#define OUT_OF_RANGE_ADDR_WIDTH        34                   
#define OUT_OF_RANGE_LENGTH_ADDR       51                   
#define OUT_OF_RANGE_LENGTH_OFFSET     8                    
#define OUT_OF_RANGE_LENGTH_WIDTH      8                    
#define OUT_OF_RANGE_SOURCE_ID_ADDR    52                   
#define OUT_OF_RANGE_SOURCE_ID_OFFSET  0                    
#define OUT_OF_RANGE_SOURCE_ID_WIDTH   11                   
#define OUT_OF_RANGE_TYPE_ADDR         51                   
#define OUT_OF_RANGE_TYPE_OFFSET       16                   
#define OUT_OF_RANGE_TYPE_WIDTH        6                    
#define PLACEMENT_EN_ADDR              42                   
#define PLACEMENT_EN_OFFSET            16                   
#define PLACEMENT_EN_WIDTH             1                    
#define PORT_CMD_ERROR_ADDR_ADDR       71                   
#define PORT_CMD_ERROR_ADDR_OFFSET     0                    
#define PORT_CMD_ERROR_ADDR_WIDTH      34                   
#define PORT_CMD_ERROR_ID_ADDR         72                   
#define PORT_CMD_ERROR_ID_OFFSET       8                    
#define PORT_CMD_ERROR_ID_WIDTH        11                   
#define PORT_CMD_ERROR_TYPE_ADDR       72                   
#define PORT_CMD_ERROR_TYPE_OFFSET     24                   
#define PORT_CMD_ERROR_TYPE_WIDTH      2                    
#define PRIORITY_EN_ADDR               42                   
#define PRIORITY_EN_OFFSET             24                   
#define PRIORITY_EN_WIDTH              1                    
#define PWRDN_SHIFT_DELAY_ADDR         22                   
#define PWRDN_SHIFT_DELAY_OFFSET       0                    
#define PWRDN_SHIFT_DELAY_WIDTH        7                    
#define PWRUP_SREFRESH_EXIT_ADDR       17                   
#define PWRUP_SREFRESH_EXIT_OFFSET     16                   
#define PWRUP_SREFRESH_EXIT_WIDTH      1                    
#define Q_FULLNESS_ADDR                46                   
#define Q_FULLNESS_OFFSET              0                    
#define Q_FULLNESS_WIDTH               4                    
#define R2R_DIFFCS_DLY_ADDR            76                   
#define R2R_DIFFCS_DLY_OFFSET          0                    
#define R2R_DIFFCS_DLY_WIDTH           3                    
#define R2R_SAMECS_DLY_ADDR            77                   
#define R2R_SAMECS_DLY_OFFSET          0                    
#define R2R_SAMECS_DLY_WIDTH           3                    
#define R2W_DIFFCS_DLY_ADDR            76                   
#define R2W_DIFFCS_DLY_OFFSET          8                    
#define R2W_DIFFCS_DLY_WIDTH           3                    
#define R2W_SAMECS_DLY_ADDR            77                   
#define R2W_SAMECS_DLY_OFFSET          8                    
#define R2W_SAMECS_DLY_WIDTH           3                    
#define RDLAT_ADJ_ADDR                 133                  
#define RDLAT_ADJ_OFFSET               0                    
#define RDLAT_ADJ_WIDTH                6                    
#define RDLVL_BEGIN_DELAY_0_ADDR       91                   
#define RDLVL_BEGIN_DELAY_0_OFFSET     0                    
#define RDLVL_BEGIN_DELAY_0_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_1_ADDR       94                   
#define RDLVL_BEGIN_DELAY_1_OFFSET     16                   
#define RDLVL_BEGIN_DELAY_1_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_2_ADDR       98                   
#define RDLVL_BEGIN_DELAY_2_OFFSET     0                    
#define RDLVL_BEGIN_DELAY_2_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_3_ADDR       101                  
#define RDLVL_BEGIN_DELAY_3_OFFSET     16                   
#define RDLVL_BEGIN_DELAY_3_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_4_ADDR       105                  
#define RDLVL_BEGIN_DELAY_4_OFFSET     0                    
#define RDLVL_BEGIN_DELAY_4_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_5_ADDR       108                  
#define RDLVL_BEGIN_DELAY_5_OFFSET     16                   
#define RDLVL_BEGIN_DELAY_5_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_6_ADDR       112                  
#define RDLVL_BEGIN_DELAY_6_OFFSET     0                    
#define RDLVL_BEGIN_DELAY_6_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_7_ADDR       115                  
#define RDLVL_BEGIN_DELAY_7_OFFSET     16                   
#define RDLVL_BEGIN_DELAY_7_WIDTH      16                   
#define RDLVL_BEGIN_DELAY_EN_ADDR      90                   
#define RDLVL_BEGIN_DELAY_EN_OFFSET    0                    
#define RDLVL_BEGIN_DELAY_EN_WIDTH     1                    
#define RDLVL_CS_ADDR                  89                   
#define RDLVL_CS_OFFSET                16                   
#define RDLVL_CS_WIDTH                 1                    
#define RDLVL_DELAY_0_ADDR             93                   
#define RDLVL_DELAY_0_OFFSET           8                    
#define RDLVL_DELAY_0_WIDTH            16                   
#define RDLVL_DELAY_1_ADDR             97                   
#define RDLVL_DELAY_1_OFFSET           0                    
#define RDLVL_DELAY_1_WIDTH            16                   
#define RDLVL_DELAY_2_ADDR             100                  
#define RDLVL_DELAY_2_OFFSET           8                    
#define RDLVL_DELAY_2_WIDTH            16                   
#define RDLVL_DELAY_3_ADDR             104                  
#define RDLVL_DELAY_3_OFFSET           0                    
#define RDLVL_DELAY_3_WIDTH            16                   
#define RDLVL_DELAY_4_ADDR             107                  
#define RDLVL_DELAY_4_OFFSET           8                    
#define RDLVL_DELAY_4_WIDTH            16                   
#define RDLVL_DELAY_5_ADDR             111                  
#define RDLVL_DELAY_5_OFFSET           0                    
#define RDLVL_DELAY_5_WIDTH            16                   
#define RDLVL_DELAY_6_ADDR             114                  
#define RDLVL_DELAY_6_OFFSET           8                    
#define RDLVL_DELAY_6_WIDTH            16                   
#define RDLVL_DELAY_7_ADDR             118                  
#define RDLVL_DELAY_7_OFFSET           0                    
#define RDLVL_DELAY_7_WIDTH            16                   
#define RDLVL_DQ_ZERO_COUNT_ADDR       148                  
#define RDLVL_DQ_ZERO_COUNT_OFFSET     0                    
#define RDLVL_DQ_ZERO_COUNT_WIDTH      4                    
#define RDLVL_EDGE_ADDR                89                   
#define RDLVL_EDGE_OFFSET              24                   
#define RDLVL_EDGE_WIDTH               1                    
#define RDLVL_EN_ADDR                  146                  
#define RDLVL_EN_OFFSET                0                    
#define RDLVL_EN_WIDTH                 1                    
#define RDLVL_END_DELAY_0_ADDR         91                   
#define RDLVL_END_DELAY_0_OFFSET       16                   
#define RDLVL_END_DELAY_0_WIDTH        16                   
#define RDLVL_END_DELAY_1_ADDR         95                   
#define RDLVL_END_DELAY_1_OFFSET       0                    
#define RDLVL_END_DELAY_1_WIDTH        16                   
#define RDLVL_END_DELAY_2_ADDR         98                   
#define RDLVL_END_DELAY_2_OFFSET       16                   
#define RDLVL_END_DELAY_2_WIDTH        16                   
#define RDLVL_END_DELAY_3_ADDR         102                  
#define RDLVL_END_DELAY_3_OFFSET       0                    
#define RDLVL_END_DELAY_3_WIDTH        16                   
#define RDLVL_END_DELAY_4_ADDR         105                  
#define RDLVL_END_DELAY_4_OFFSET       16                   
#define RDLVL_END_DELAY_4_WIDTH        16                   
#define RDLVL_END_DELAY_5_ADDR         109                  
#define RDLVL_END_DELAY_5_OFFSET       0                    
#define RDLVL_END_DELAY_5_WIDTH        16                   
#define RDLVL_END_DELAY_6_ADDR         112                  
#define RDLVL_END_DELAY_6_OFFSET       16                   
#define RDLVL_END_DELAY_6_WIDTH        16                   
#define RDLVL_END_DELAY_7_ADDR         116                  
#define RDLVL_END_DELAY_7_OFFSET       0                    
#define RDLVL_END_DELAY_7_WIDTH        16                   
#define RDLVL_ERROR_STATUS_ADDR        149                  
#define RDLVL_ERROR_STATUS_OFFSET      0                    
#define RDLVL_ERROR_STATUS_WIDTH       34                   
#define RDLVL_GATE_DELAY_0_ADDR        94                   
#define RDLVL_GATE_DELAY_0_OFFSET      0                    
#define RDLVL_GATE_DELAY_0_WIDTH       16                   
#define RDLVL_GATE_DELAY_1_ADDR        97                   
#define RDLVL_GATE_DELAY_1_OFFSET      16                   
#define RDLVL_GATE_DELAY_1_WIDTH       16                   
#define RDLVL_GATE_DELAY_2_ADDR        101                  
#define RDLVL_GATE_DELAY_2_OFFSET      0                    
#define RDLVL_GATE_DELAY_2_WIDTH       16                   
#define RDLVL_GATE_DELAY_3_ADDR        104                  
#define RDLVL_GATE_DELAY_3_OFFSET      16                   
#define RDLVL_GATE_DELAY_3_WIDTH       16                   
#define RDLVL_GATE_DELAY_4_ADDR        108                  
#define RDLVL_GATE_DELAY_4_OFFSET      0                    
#define RDLVL_GATE_DELAY_4_WIDTH       16                   
#define RDLVL_GATE_DELAY_5_ADDR        111                  
#define RDLVL_GATE_DELAY_5_OFFSET      16                   
#define RDLVL_GATE_DELAY_5_WIDTH       16                   
#define RDLVL_GATE_DELAY_6_ADDR        115                  
#define RDLVL_GATE_DELAY_6_OFFSET      0                    
#define RDLVL_GATE_DELAY_6_WIDTH       16                   
#define RDLVL_GATE_DELAY_7_ADDR        118                  
#define RDLVL_GATE_DELAY_7_OFFSET      16                   
#define RDLVL_GATE_DELAY_7_WIDTH       16                   
#define RDLVL_GATE_DQ_ZERO_COUNT_ADDR  148                  
#define RDLVL_GATE_DQ_ZERO_COUNT_OFFSET 8                    
#define RDLVL_GATE_DQ_ZERO_COUNT_WIDTH 4                    
#define RDLVL_GATE_EN_ADDR             146                  
#define RDLVL_GATE_EN_OFFSET           8                    
#define RDLVL_GATE_EN_WIDTH            1                    
#define RDLVL_GATE_INTERVAL_ADDR       151                  
#define RDLVL_GATE_INTERVAL_OFFSET     0                    
#define RDLVL_GATE_INTERVAL_WIDTH      16                   
#define RDLVL_GATE_MAX_DELAY_ADDR      140                  
#define RDLVL_GATE_MAX_DELAY_OFFSET    0                    
#define RDLVL_GATE_MAX_DELAY_WIDTH     16                   
#define RDLVL_GATE_PREAMBLE_CHECK_EN_ADDR 146                  
#define RDLVL_GATE_PREAMBLE_CHECK_EN_OFFSET 16                   
#define RDLVL_GATE_PREAMBLE_CHECK_EN_WIDTH 1                    
#define RDLVL_GATE_REG_EN_ADDR         90                   
#define RDLVL_GATE_REG_EN_OFFSET       16                   
#define RDLVL_GATE_REG_EN_WIDTH        1                    
#define RDLVL_GATE_REQ_ADDR            89                   
#define RDLVL_GATE_REQ_OFFSET          8                    
#define RDLVL_GATE_REQ_WIDTH           1                    
#define RDLVL_GATE_RESP_MASK_ADDR      144                  
#define RDLVL_GATE_RESP_MASK_OFFSET    0                    
#define RDLVL_GATE_RESP_MASK_WIDTH     64                   
#define RDLVL_INTERVAL_ADDR            150                  
#define RDLVL_INTERVAL_OFFSET          8                    
#define RDLVL_INTERVAL_WIDTH           16                   
#define RDLVL_MAX_DELAY_ADDR           139                  
#define RDLVL_MAX_DELAY_OFFSET         8                    
#define RDLVL_MAX_DELAY_WIDTH          16                   
#define RDLVL_MIDPOINT_DELAY_0_ADDR    92                   
#define RDLVL_MIDPOINT_DELAY_0_OFFSET  0                    
#define RDLVL_MIDPOINT_DELAY_0_WIDTH   16                   
#define RDLVL_MIDPOINT_DELAY_1_ADDR    95                   
#define RDLVL_MIDPOINT_DELAY_1_OFFSET  16                   
#define RDLVL_MIDPOINT_DELAY_1_WIDTH   16                   
#define RDLVL_MIDPOINT_DELAY_2_ADDR    99                   
#define RDLVL_MIDPOINT_DELAY_2_OFFSET  0                    
#define RDLVL_MIDPOINT_DELAY_2_WIDTH   16                   
#define RDLVL_MIDPOINT_DELAY_3_ADDR    102                  
#define RDLVL_MIDPOINT_DELAY_3_OFFSET  16                   
#define RDLVL_MIDPOINT_DELAY_3_WIDTH   16                   
#define RDLVL_MIDPOINT_DELAY_4_ADDR    106                  
#define RDLVL_MIDPOINT_DELAY_4_OFFSET  0                    
#define RDLVL_MIDPOINT_DELAY_4_WIDTH   16                   
#define RDLVL_MIDPOINT_DELAY_5_ADDR    109                  
#define RDLVL_MIDPOINT_DELAY_5_OFFSET  16                   
#define RDLVL_MIDPOINT_DELAY_5_WIDTH   16                   
#define RDLVL_MIDPOINT_DELAY_6_ADDR    113                  
#define RDLVL_MIDPOINT_DELAY_6_OFFSET  0                    
#define RDLVL_MIDPOINT_DELAY_6_WIDTH   16                   
#define RDLVL_MIDPOINT_DELAY_7_ADDR    116                  
#define RDLVL_MIDPOINT_DELAY_7_OFFSET  16                   
#define RDLVL_MIDPOINT_DELAY_7_WIDTH   16                   
#define RDLVL_OFFSET_DELAY_0_ADDR      92                   
#define RDLVL_OFFSET_DELAY_0_OFFSET    16                   
#define RDLVL_OFFSET_DELAY_0_WIDTH     16                   
#define RDLVL_OFFSET_DELAY_1_ADDR      96                   
#define RDLVL_OFFSET_DELAY_1_OFFSET    0                    
#define RDLVL_OFFSET_DELAY_1_WIDTH     16                   
#define RDLVL_OFFSET_DELAY_2_ADDR      99                   
#define RDLVL_OFFSET_DELAY_2_OFFSET    16                   
#define RDLVL_OFFSET_DELAY_2_WIDTH     16                   
#define RDLVL_OFFSET_DELAY_3_ADDR      103                  
#define RDLVL_OFFSET_DELAY_3_OFFSET    0                    
#define RDLVL_OFFSET_DELAY_3_WIDTH     16                   
#define RDLVL_OFFSET_DELAY_4_ADDR      106                  
#define RDLVL_OFFSET_DELAY_4_OFFSET    16                   
#define RDLVL_OFFSET_DELAY_4_WIDTH     16                   
#define RDLVL_OFFSET_DELAY_5_ADDR      110                  
#define RDLVL_OFFSET_DELAY_5_OFFSET    0                    
#define RDLVL_OFFSET_DELAY_5_WIDTH     16                   
#define RDLVL_OFFSET_DELAY_6_ADDR      113                  
#define RDLVL_OFFSET_DELAY_6_OFFSET    16                   
#define RDLVL_OFFSET_DELAY_6_WIDTH     16                   
#define RDLVL_OFFSET_DELAY_7_ADDR      117                  
#define RDLVL_OFFSET_DELAY_7_OFFSET    0                    
#define RDLVL_OFFSET_DELAY_7_WIDTH     16                   
#define RDLVL_OFFSET_DIR_0_ADDR        93                   
#define RDLVL_OFFSET_DIR_0_OFFSET      0                    
#define RDLVL_OFFSET_DIR_0_WIDTH       1                    
#define RDLVL_OFFSET_DIR_1_ADDR        96                   
#define RDLVL_OFFSET_DIR_1_OFFSET      16                   
#define RDLVL_OFFSET_DIR_1_WIDTH       1                    
#define RDLVL_OFFSET_DIR_2_ADDR        100                  
#define RDLVL_OFFSET_DIR_2_OFFSET      0                    
#define RDLVL_OFFSET_DIR_2_WIDTH       1                    
#define RDLVL_OFFSET_DIR_3_ADDR        103                  
#define RDLVL_OFFSET_DIR_3_OFFSET      16                   
#define RDLVL_OFFSET_DIR_3_WIDTH       1                    
#define RDLVL_OFFSET_DIR_4_ADDR        107                  
#define RDLVL_OFFSET_DIR_4_OFFSET      0                    
#define RDLVL_OFFSET_DIR_4_WIDTH       1                    
#define RDLVL_OFFSET_DIR_5_ADDR        110                  
#define RDLVL_OFFSET_DIR_5_OFFSET      16                   
#define RDLVL_OFFSET_DIR_5_WIDTH       1                    
#define RDLVL_OFFSET_DIR_6_ADDR        114                  
#define RDLVL_OFFSET_DIR_6_OFFSET      0                    
#define RDLVL_OFFSET_DIR_6_WIDTH       1                    
#define RDLVL_OFFSET_DIR_7_ADDR        117                  
#define RDLVL_OFFSET_DIR_7_OFFSET      16                   
#define RDLVL_OFFSET_DIR_7_WIDTH       1                    
#define RDLVL_REG_EN_ADDR              90                   
#define RDLVL_REG_EN_OFFSET            8                    
#define RDLVL_REG_EN_WIDTH             1                    
#define RDLVL_REQ_ADDR                 89                   
#define RDLVL_REQ_OFFSET               0                    
#define RDLVL_REQ_WIDTH                1                    
#define RDLVL_RESP_MASK_ADDR           142                  
#define RDLVL_RESP_MASK_OFFSET         0                    
#define RDLVL_RESP_MASK_WIDTH          64                   
#define RD_TO_ODTH_ADDR                160                  
#define RD_TO_ODTH_OFFSET              16                   
#define RD_TO_ODTH_WIDTH               5                    
#define READ_DATA_FIFO_DEPTH_ADDR      151                  
#define READ_DATA_FIFO_DEPTH_OFFSET    24                   
#define READ_DATA_FIFO_DEPTH_WIDTH     8                    
#define READ_DATA_FIFO_PTR_WIDTH_ADDR  152                  
#define READ_DATA_FIFO_PTR_WIDTH_OFFSET 0                    
#define READ_DATA_FIFO_PTR_WIDTH_WIDTH 8                    
#define REDUC_ADDR                     45                   
#define REDUC_OFFSET                   24                   
#define REDUC_WIDTH                    1                    
#define REG_DIMM_ENABLE_ADDR           12                   
#define REG_DIMM_ENABLE_OFFSET         16                   
#define REG_DIMM_ENABLE_WIDTH          1                    
#define ROW_DIFF_ADDR                  40                   
#define ROW_DIFF_OFFSET                24                   
#define ROW_DIFF_WIDTH                 3                    
#define RW_SAME_EN_ADDR                43                   
#define RW_SAME_EN_OFFSET              0                    
#define RW_SAME_EN_WIDTH               1                    
#define RW_SAME_PAGE_EN_ADDR           43                   
#define RW_SAME_PAGE_EN_OFFSET         8                    
#define RW_SAME_PAGE_EN_WIDTH          1                    
#define SREFRESH_EXIT_NO_REFRESH_ADDR  17                   
#define SREFRESH_EXIT_NO_REFRESH_OFFSET 24                   
#define SREFRESH_EXIT_NO_REFRESH_WIDTH 1                    
#define START_ADDR                     0                    
#define START_OFFSET                   0                    
#define START_WIDTH                    1                    
#define SWAP_EN_ADDR                   44                   
#define SWAP_EN_OFFSET                 16                   
#define SWAP_EN_WIDTH                  1                    
#define SWLVL_EXIT_ADDR                78                   
#define SWLVL_EXIT_OFFSET              24                   
#define SWLVL_EXIT_WIDTH               1                    
#define SWLVL_LOAD_ADDR                78                   
#define SWLVL_LOAD_OFFSET              8                    
#define SWLVL_LOAD_WIDTH               1                    
#define SWLVL_OP_DONE_ADDR             79                   
#define SWLVL_OP_DONE_OFFSET           0                    
#define SWLVL_OP_DONE_WIDTH            1                    
#define SWLVL_RESP_0_ADDR              79                   
#define SWLVL_RESP_0_OFFSET            16                   
#define SWLVL_RESP_0_WIDTH             8                    
#define SWLVL_RESP_1_ADDR              79                   
#define SWLVL_RESP_1_OFFSET            24                   
#define SWLVL_RESP_1_WIDTH             8                    
#define SWLVL_RESP_2_ADDR              80                   
#define SWLVL_RESP_2_OFFSET            0                    
#define SWLVL_RESP_2_WIDTH             8                    
#define SWLVL_RESP_3_ADDR              80                   
#define SWLVL_RESP_3_OFFSET            8                    
#define SWLVL_RESP_3_WIDTH             8                    
#define SWLVL_RESP_4_ADDR              80                   
#define SWLVL_RESP_4_OFFSET            16                   
#define SWLVL_RESP_4_WIDTH             8                    
#define SWLVL_RESP_5_ADDR              80                   
#define SWLVL_RESP_5_OFFSET            24                   
#define SWLVL_RESP_5_WIDTH             8                    
#define SWLVL_RESP_6_ADDR              81                   
#define SWLVL_RESP_6_OFFSET            0                    
#define SWLVL_RESP_6_WIDTH             8                    
#define SWLVL_RESP_7_ADDR              81                   
#define SWLVL_RESP_7_OFFSET            8                    
#define SWLVL_RESP_7_WIDTH             8                    
#define SWLVL_START_ADDR               78                   
#define SWLVL_START_OFFSET             16                   
#define SWLVL_START_WIDTH              1                    
#define SW_LEVELING_MODE_ADDR          78                   
#define SW_LEVELING_MODE_OFFSET        0                    
#define SW_LEVELING_MODE_WIDTH         2                    
#define TBST_INT_INTERVAL_ADDR         5                    
#define TBST_INT_INTERVAL_OFFSET       24                   
#define TBST_INT_INTERVAL_WIDTH        3                    
#define TCCD_ADDR                      6                    
#define TCCD_OFFSET                    0                    
#define TCCD_WIDTH                     5                    
#define TCKE_ADDR                      9                    
#define TCKE_OFFSET                    24                   
#define TCKE_WIDTH                     3                    
#define TCKESR_ADDR                    10                   
#define TCKESR_OFFSET                  0                    
#define TCKESR_WIDTH                   8                    
#define TDAL_ADDR                      11                   
#define TDAL_OFFSET                    24                   
#define TDAL_WIDTH                     6                    
#define TDFI_CTRLUPD_INTERVAL_ADDR     132                  
#define TDFI_CTRLUPD_INTERVAL_OFFSET   0                    
#define TDFI_CTRLUPD_INTERVAL_WIDTH    32                   
#define TDFI_CTRLUPD_MAX_ADDR          128                  
#define TDFI_CTRLUPD_MAX_OFFSET        8                    
#define TDFI_CTRLUPD_MAX_WIDTH         14                   
#define TDFI_CTRLUPD_MIN_ADDR          128                  
#define TDFI_CTRLUPD_MIN_OFFSET        0                    
#define TDFI_CTRLUPD_MIN_WIDTH         4                    
#define TDFI_CTRL_DELAY_ADDR           133                  
#define TDFI_CTRL_DELAY_OFFSET         16                   
#define TDFI_CTRL_DELAY_WIDTH          4                    
#define TDFI_DRAM_CLK_DISABLE_ADDR     133                  
#define TDFI_DRAM_CLK_DISABLE_OFFSET   24                   
#define TDFI_DRAM_CLK_DISABLE_WIDTH    4                    
#define TDFI_DRAM_CLK_ENABLE_ADDR      134                  
#define TDFI_DRAM_CLK_ENABLE_OFFSET    0                    
#define TDFI_DRAM_CLK_ENABLE_WIDTH     4                    
#define TDFI_PHYUPD_RESP_ADDR          131                  
#define TDFI_PHYUPD_RESP_OFFSET        0                    
#define TDFI_PHYUPD_RESP_WIDTH         14                   
#define TDFI_PHYUPD_TYPE0_ADDR         129                  
#define TDFI_PHYUPD_TYPE0_OFFSET       0                    
#define TDFI_PHYUPD_TYPE0_WIDTH        16                   
#define TDFI_PHYUPD_TYPE1_ADDR         129                  
#define TDFI_PHYUPD_TYPE1_OFFSET       16                   
#define TDFI_PHYUPD_TYPE1_WIDTH        16                   
#define TDFI_PHYUPD_TYPE2_ADDR         130                  
#define TDFI_PHYUPD_TYPE2_OFFSET       0                    
#define TDFI_PHYUPD_TYPE2_WIDTH        16                   
#define TDFI_PHYUPD_TYPE3_ADDR         130                  
#define TDFI_PHYUPD_TYPE3_OFFSET       16                   
#define TDFI_PHYUPD_TYPE3_WIDTH        16                   
#define TDFI_PHY_RDLAT_ADDR            127                  
#define TDFI_PHY_RDLAT_OFFSET          8                    
#define TDFI_PHY_RDLAT_WIDTH           6                    
#define TDFI_PHY_WRDATA_ADDR           151                  
#define TDFI_PHY_WRDATA_OFFSET         16                   
#define TDFI_PHY_WRDATA_WIDTH          3                    
#define TDFI_PHY_WRLAT_ADDR            126                  
#define TDFI_PHY_WRLAT_OFFSET          24                   
#define TDFI_PHY_WRLAT_WIDTH           6                    
#define TDFI_RDDATA_EN_ADDR            127                  
#define TDFI_RDDATA_EN_OFFSET          16                   
#define TDFI_RDDATA_EN_WIDTH           6                    
#define TDFI_RDLVL_DLL_ADDR            138                  
#define TDFI_RDLVL_DLL_OFFSET          16                   
#define TDFI_RDLVL_DLL_WIDTH           8                    
#define TDFI_RDLVL_EN_ADDR             138                  
#define TDFI_RDLVL_EN_OFFSET           8                    
#define TDFI_RDLVL_EN_WIDTH            8                    
#define TDFI_RDLVL_LOAD_ADDR           138                  
#define TDFI_RDLVL_LOAD_OFFSET         24                   
#define TDFI_RDLVL_LOAD_WIDTH          8                    
#define TDFI_RDLVL_MAX_ADDR            147                  
#define TDFI_RDLVL_MAX_OFFSET          0                    
#define TDFI_RDLVL_MAX_WIDTH           32                   
#define TDFI_RDLVL_RESP_ADDR           141                  
#define TDFI_RDLVL_RESP_OFFSET         0                    
#define TDFI_RDLVL_RESP_WIDTH          32                   
#define TDFI_RDLVL_RESPLAT_ADDR        139                  
#define TDFI_RDLVL_RESPLAT_OFFSET      0                    
#define TDFI_RDLVL_RESPLAT_WIDTH       8                    
#define TDFI_RDLVL_RR_ADDR             140                  
#define TDFI_RDLVL_RR_OFFSET           16                   
#define TDFI_RDLVL_RR_WIDTH            10                   
#define TDFI_WRLVL_DLL_ADDR            137                  
#define TDFI_WRLVL_DLL_OFFSET          16                   
#define TDFI_WRLVL_DLL_WIDTH           8                    
#define TDFI_WRLVL_EN_ADDR             134                  
#define TDFI_WRLVL_EN_OFFSET           8                    
#define TDFI_WRLVL_EN_WIDTH            8                    
#define TDFI_WRLVL_LOAD_ADDR           138                  
#define TDFI_WRLVL_LOAD_OFFSET         0                    
#define TDFI_WRLVL_LOAD_WIDTH          8                    
#define TDFI_WRLVL_MAX_ADDR            136                  
#define TDFI_WRLVL_MAX_OFFSET          0                    
#define TDFI_WRLVL_MAX_WIDTH           32                   
#define TDFI_WRLVL_RESP_ADDR           135                  
#define TDFI_WRLVL_RESP_OFFSET         0                    
#define TDFI_WRLVL_RESP_WIDTH          32                   
#define TDFI_WRLVL_RESPLAT_ADDR        137                  
#define TDFI_WRLVL_RESPLAT_OFFSET      24                   
#define TDFI_WRLVL_RESPLAT_WIDTH       8                    
#define TDFI_WRLVL_WW_ADDR             134                  
#define TDFI_WRLVL_WW_OFFSET           16                   
#define TDFI_WRLVL_WW_WIDTH            10                   
#define TFAW_ADDR                      7                    
#define TFAW_OFFSET                    16                   
#define TFAW_WIDTH                     6                    
#define TINIT_ADDR                     2                    
#define TINIT_OFFSET                   0                    
#define TINIT_WIDTH                    24                   
#define TMOD_ADDR                      8                    
#define TMOD_OFFSET                    8                    
#define TMOD_WIDTH                     8                    
#define TMRD_ADDR                      8                    
#define TMRD_OFFSET                    0                    
#define TMRD_WIDTH                     5                    
#define TODTH_RD_ADDR                  74                   
#define TODTH_RD_OFFSET                16                   
#define TODTH_RD_WIDTH                 4                    
#define TODTH_WR_ADDR                  74                   
#define TODTH_WR_OFFSET                8                    
#define TODTH_WR_WIDTH                 4                    
#define TODTL_2CMD_ADDR                74                   
#define TODTL_2CMD_OFFSET              0                    
#define TODTL_2CMD_WIDTH               5                    
#define TPDEX_ADDR                     15                   
#define TPDEX_OFFSET                   8                    
#define TPDEX_WIDTH                    16                   
#define TRAS_LOCKOUT_ADDR              11                   
#define TRAS_LOCKOUT_OFFSET            16                   
#define TRAS_LOCKOUT_WIDTH             1                    
#define TRAS_MAX_ADDR                  9                    
#define TRAS_MAX_OFFSET                0                    
#define TRAS_MAX_WIDTH                 17                   
#define TRAS_MIN_ADDR                  6                    
#define TRAS_MIN_OFFSET                24                   
#define TRAS_MIN_WIDTH                 8                    
#define TRC_ADDR                       6                    
#define TRC_OFFSET                     16                   
#define TRC_WIDTH                      8                    
#define TRCD_ADDR                      10                   
#define TRCD_OFFSET                    16                   
#define TRCD_WIDTH                     8                    
#define TREF_ADDR                      14                   
#define TREF_OFFSET                    16                   
#define TREF_WIDTH                     14                   
#define TREF_ENABLE_ADDR               13                   
#define TREF_ENABLE_OFFSET             16                   
#define TREF_ENABLE_WIDTH              1                    
#define TRFC_ADDR                      14                   
#define TRFC_OFFSET                    0                    
#define TRFC_WIDTH                     10                   
#define TRP_ADDR                       7                    
#define TRP_OFFSET                     8                    
#define TRP_WIDTH                      5                    
#define TRP_AB_ADDR                    12                   
#define TRP_AB_OFFSET                  8                    
#define TRP_AB_WIDTH                   5                    
#define TRRD_ADDR                      6                    
#define TRRD_OFFSET                    8                    
#define TRRD_WIDTH                     8                    
#define TRST_PWRON_ADDR                3                    
#define TRST_PWRON_OFFSET              0                    
#define TRST_PWRON_WIDTH               32                   
#define TRTP_ADDR                      7                    
#define TRTP_OFFSET                    24                   
#define TRTP_WIDTH                     4                    
#define TWR_ADDR                       10                   
#define TWR_OFFSET                     24                   
#define TWR_WIDTH                      6                    
#define TWTR_ADDR                      7                    
#define TWTR_OFFSET                    0                    
#define TWTR_WIDTH                     4                    
#define TXPDLL_ADDR                    16                   
#define TXPDLL_OFFSET                  0                    
#define TXPDLL_WIDTH                   16                   
#define TXSNR_ADDR                     17                   
#define TXSNR_OFFSET                   0                    
#define TXSNR_WIDTH                    16                   
#define TXSR_ADDR                      16                   
#define TXSR_OFFSET                    16                   
#define TXSR_WIDTH                     16                   
#define UPDATE_ERROR_STATUS_ADDR       127                  
#define UPDATE_ERROR_STATUS_OFFSET     0                    
#define UPDATE_ERROR_STATUS_WIDTH      7                    
#define VERSION_ADDR                   0                    
#define VERSION_OFFSET                 16                   
#define VERSION_WIDTH                  16                   
#define W2R_DIFFCS_DLY_ADDR            76                   
#define W2R_DIFFCS_DLY_OFFSET          16                   
#define W2R_DIFFCS_DLY_WIDTH           3                    
#define W2R_SAMECS_DLY_ADDR            77                   
#define W2R_SAMECS_DLY_OFFSET          16                   
#define W2R_SAMECS_DLY_WIDTH           3                    
#define W2R_SPLIT_EN_ADDR              43                   
#define W2R_SPLIT_EN_OFFSET            24                   
#define W2R_SPLIT_EN_WIDTH             1                    
#define W2W_DIFFCS_DLY_ADDR            76                   
#define W2W_DIFFCS_DLY_OFFSET          24                   
#define W2W_DIFFCS_DLY_WIDTH           3                    
#define W2W_SAMECS_DLY_ADDR            77                   
#define W2W_SAMECS_DLY_OFFSET          24                   
#define W2W_SAMECS_DLY_WIDTH           3                    
#define WLDQSEN_ADDR                   82                   
#define WLDQSEN_OFFSET                 0                    
#define WLDQSEN_WIDTH                  6                    
#define WLMRD_ADDR                     82                   
#define WLMRD_OFFSET                   8                    
#define WLMRD_WIDTH                    6                    
#define WRITEINTERP_ADDR               10                   
#define WRITEINTERP_OFFSET             8                    
#define WRITEINTERP_WIDTH              1                    
#define WRITE_DATA_FIFO_DEPTH_ADDR     152                  
#define WRITE_DATA_FIFO_DEPTH_OFFSET   8                    
#define WRITE_DATA_FIFO_DEPTH_WIDTH    8                    
#define WRITE_DATA_FIFO_PTR_WIDTH_ADDR 152                  
#define WRITE_DATA_FIFO_PTR_WIDTH_OFFSET 16                   
#define WRITE_DATA_FIFO_PTR_WIDTH_WIDTH 8                    
#define WRITE_MODEREG_ADDR             23                   
#define WRITE_MODEREG_OFFSET           0                    
#define WRITE_MODEREG_WIDTH            26                   
#define WRLAT_ADDR                     5                    
#define WRLAT_OFFSET                   8                    
#define WRLAT_WIDTH                    5                    
#define WRLAT_ADJ_ADDR                 133                  
#define WRLAT_ADJ_OFFSET               8                    
#define WRLAT_ADJ_WIDTH                6                    
#define WRLVL_CS_ADDR                  81                   
#define WRLVL_CS_OFFSET                24                   
#define WRLVL_CS_WIDTH                 1                    
#define WRLVL_DELAY_0_ADDR             85                   
#define WRLVL_DELAY_0_OFFSET           0                    
#define WRLVL_DELAY_0_WIDTH            16                   
#define WRLVL_DELAY_1_ADDR             85                   
#define WRLVL_DELAY_1_OFFSET           16                   
#define WRLVL_DELAY_1_WIDTH            16                   
#define WRLVL_DELAY_2_ADDR             86                   
#define WRLVL_DELAY_2_OFFSET           0                    
#define WRLVL_DELAY_2_WIDTH            16                   
#define WRLVL_DELAY_3_ADDR             86                   
#define WRLVL_DELAY_3_OFFSET           16                   
#define WRLVL_DELAY_3_WIDTH            16                   
#define WRLVL_DELAY_4_ADDR             87                   
#define WRLVL_DELAY_4_OFFSET           0                    
#define WRLVL_DELAY_4_WIDTH            16                   
#define WRLVL_DELAY_5_ADDR             87                   
#define WRLVL_DELAY_5_OFFSET           16                   
#define WRLVL_DELAY_5_WIDTH            16                   
#define WRLVL_DELAY_6_ADDR             88                   
#define WRLVL_DELAY_6_OFFSET           0                    
#define WRLVL_DELAY_6_WIDTH            16                   
#define WRLVL_DELAY_7_ADDR             88                   
#define WRLVL_DELAY_7_OFFSET           16                   
#define WRLVL_DELAY_7_WIDTH            16                   
#define WRLVL_EN_ADDR                  82                   
#define WRLVL_EN_OFFSET                16                   
#define WRLVL_EN_WIDTH                 1                    
#define WRLVL_ERROR_STATUS_ADDR        84                   
#define WRLVL_ERROR_STATUS_OFFSET      0                    
#define WRLVL_ERROR_STATUS_WIDTH       18                   
#define WRLVL_INTERVAL_ADDR            83                   
#define WRLVL_INTERVAL_OFFSET          0                    
#define WRLVL_INTERVAL_WIDTH           16                   
#define WRLVL_REG_EN_ADDR              84                   
#define WRLVL_REG_EN_OFFSET            24                   
#define WRLVL_REG_EN_WIDTH             1                    
#define WRLVL_REQ_ADDR                 81                   
#define WRLVL_REQ_OFFSET               16                   
#define WRLVL_REQ_WIDTH                1                    
#define WRLVL_RESP_MASK_ADDR           160                  
#define WRLVL_RESP_MASK_OFFSET         24                   
#define WRLVL_RESP_MASK_WIDTH          8                    
#define WR_TO_ODTH_ADDR                160                  
#define WR_TO_ODTH_OFFSET              8                    
#define WR_TO_ODTH_WIDTH               5                    
#define ZQCL_ADDR                      37                   
#define ZQCL_OFFSET                    16                   
#define ZQCL_WIDTH                     12                   
#define ZQCS_ADDR                      38                   
#define ZQCS_OFFSET                    0                    
#define ZQCS_WIDTH                     12                   
#define ZQCS_ROTATE_ADDR               40                   
#define ZQCS_ROTATE_OFFSET             8                    
#define ZQCS_ROTATE_WIDTH              1                    
#define ZQINIT_ADDR                    37                   
#define ZQINIT_OFFSET                  0                    
#define ZQINIT_WIDTH                   12                   
#define ZQ_INTERVAL_ADDR               159                  
#define ZQ_INTERVAL_OFFSET             0                    
#define ZQ_INTERVAL_WIDTH              32                   
#define ZQ_IN_PROGRESS_ADDR            40                   
#define ZQ_IN_PROGRESS_OFFSET          0                    
#define ZQ_IN_PROGRESS_WIDTH           1                    
#define ZQ_ON_SREF_EXIT_ADDR           38                   
#define ZQ_ON_SREF_EXIT_OFFSET         24                   
#define ZQ_ON_SREF_EXIT_WIDTH          2                    
#define ZQ_REQ_ADDR                    38                   
#define ZQ_REQ_OFFSET                  16                   
#define ZQ_REQ_WIDTH                   2

#define DEN_PHY_CTRL_REG_ADDR          0 + PHY_AC_BASE_ADDR 
#define DEN_PHY_CTRL_REG_OFFSET        0                    
#define DEN_PHY_CTRL_REG_WIDTH         32                   
#define DEN_PHY_DQS_TIMING_REG_ADDR    1                    
#define DEN_PHY_DQS_TIMING_REG_OFFSET  0                    
#define DEN_PHY_DQS_TIMING_REG_WIDTH   32                   
#define DEN_PHY_DQS_TIMING_REG_0_ADDR  1   
#define DEN_PHY_DQS_TIMING_REG_0_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_0_WIDTH 32                   
#define DEN_PHY_DQS_TIMING_REG_1_ADDR  17  
#define DEN_PHY_DQS_TIMING_REG_1_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_1_WIDTH 32                   
#define DEN_PHY_DQS_TIMING_REG_2_ADDR  33  
#define DEN_PHY_DQS_TIMING_REG_2_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_2_WIDTH 32                   
#define DEN_PHY_DQS_TIMING_REG_3_ADDR  49  
#define DEN_PHY_DQS_TIMING_REG_3_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_3_WIDTH 32                   
#define DEN_PHY_DQS_TIMING_REG_4_ADDR  65  
#define DEN_PHY_DQS_TIMING_REG_4_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_4_WIDTH 32                   
#define DEN_PHY_DQS_TIMING_REG_5_ADDR  81  
#define DEN_PHY_DQS_TIMING_REG_5_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_5_WIDTH 32                   
#define DEN_PHY_DQS_TIMING_REG_6_ADDR  97  
#define DEN_PHY_DQS_TIMING_REG_6_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_6_WIDTH 32                   
#define DEN_PHY_DQS_TIMING_REG_7_ADDR  113 
#define DEN_PHY_DQS_TIMING_REG_7_OFFSET 0                    
#define DEN_PHY_DQS_TIMING_REG_7_WIDTH 32                   
#define DEN_PHY_DQ_TIMING_REG_ADDR     0                    
#define DEN_PHY_DQ_TIMING_REG_OFFSET   0                    
#define DEN_PHY_DQ_TIMING_REG_WIDTH    32                   
#define DEN_PHY_DQ_TIMING_REG_0_ADDR   0   
#define DEN_PHY_DQ_TIMING_REG_0_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_0_WIDTH  32                   
#define DEN_PHY_DQ_TIMING_REG_1_ADDR   16  
#define DEN_PHY_DQ_TIMING_REG_1_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_1_WIDTH  32                   
#define DEN_PHY_DQ_TIMING_REG_2_ADDR   32  
#define DEN_PHY_DQ_TIMING_REG_2_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_2_WIDTH  32                   
#define DEN_PHY_DQ_TIMING_REG_3_ADDR   48  
#define DEN_PHY_DQ_TIMING_REG_3_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_3_WIDTH  32                   
#define DEN_PHY_DQ_TIMING_REG_4_ADDR   64  
#define DEN_PHY_DQ_TIMING_REG_4_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_4_WIDTH  32                   
#define DEN_PHY_DQ_TIMING_REG_5_ADDR   80  
#define DEN_PHY_DQ_TIMING_REG_5_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_5_WIDTH  32                   
#define DEN_PHY_DQ_TIMING_REG_6_ADDR   96  
#define DEN_PHY_DQ_TIMING_REG_6_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_6_WIDTH  32                   
#define DEN_PHY_DQ_TIMING_REG_7_ADDR   112 
#define DEN_PHY_DQ_TIMING_REG_7_OFFSET 0                    
#define DEN_PHY_DQ_TIMING_REG_7_WIDTH  32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_ADDR 2                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_0_ADDR 2   
#define DEN_PHY_GATE_LPBK_CTRL_REG_0_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_0_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_1_ADDR 18  
#define DEN_PHY_GATE_LPBK_CTRL_REG_1_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_1_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_2_ADDR 34  
#define DEN_PHY_GATE_LPBK_CTRL_REG_2_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_2_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_3_ADDR 50  
#define DEN_PHY_GATE_LPBK_CTRL_REG_3_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_3_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_4_ADDR 66  
#define DEN_PHY_GATE_LPBK_CTRL_REG_4_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_4_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_5_ADDR 82  
#define DEN_PHY_GATE_LPBK_CTRL_REG_5_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_5_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_6_ADDR 98  
#define DEN_PHY_GATE_LPBK_CTRL_REG_6_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_6_WIDTH 32                   
#define DEN_PHY_GATE_LPBK_CTRL_REG_7_ADDR 114 
#define DEN_PHY_GATE_LPBK_CTRL_REG_7_OFFSET 0                    
#define DEN_PHY_GATE_LPBK_CTRL_REG_7_WIDTH 32                   
#define DEN_PHY_OBS_REG_0_ADDR         6                    
#define DEN_PHY_OBS_REG_0_OFFSET       0                    
#define DEN_PHY_OBS_REG_0_WIDTH        32                   
#define DEN_PHY_OBS_REG_0_0_ADDR       6   
#define DEN_PHY_OBS_REG_0_0_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_0_WIDTH      32                   
#define DEN_PHY_OBS_REG_0_1_ADDR       22  
#define DEN_PHY_OBS_REG_0_1_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_1_WIDTH      32                   
#define DEN_PHY_OBS_REG_0_2_ADDR       38  
#define DEN_PHY_OBS_REG_0_2_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_2_WIDTH      32                   
#define DEN_PHY_OBS_REG_0_3_ADDR       54  
#define DEN_PHY_OBS_REG_0_3_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_3_WIDTH      32                   
#define DEN_PHY_OBS_REG_0_4_ADDR       70  
#define DEN_PHY_OBS_REG_0_4_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_4_WIDTH      32                   
#define DEN_PHY_OBS_REG_0_5_ADDR       86  
#define DEN_PHY_OBS_REG_0_5_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_5_WIDTH      32                   
#define DEN_PHY_OBS_REG_0_6_ADDR       102 
#define DEN_PHY_OBS_REG_0_6_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_6_WIDTH      32                   
#define DEN_PHY_OBS_REG_0_7_ADDR       118 
#define DEN_PHY_OBS_REG_0_7_OFFSET     0                    
#define DEN_PHY_OBS_REG_0_7_WIDTH      32                   
#define DEN_PHY_PAD_TSEL_REG_ADDR      1 + PHY_AC_BASE_ADDR 
#define DEN_PHY_PAD_TSEL_REG_OFFSET    0                    
#define DEN_PHY_PAD_TSEL_REG_WIDTH     32                   
#define DEN_PHY_READ_CTRL_REG_ADDR     3                    
#define DEN_PHY_READ_CTRL_REG_OFFSET   0                    
#define DEN_PHY_READ_CTRL_REG_WIDTH    32                   
#define DEN_PHY_READ_CTRL_REG_0_ADDR   3   
#define DEN_PHY_READ_CTRL_REG_0_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_0_WIDTH  32                   
#define DEN_PHY_READ_CTRL_REG_1_ADDR   19  
#define DEN_PHY_READ_CTRL_REG_1_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_1_WIDTH  32                   
#define DEN_PHY_READ_CTRL_REG_2_ADDR   35  
#define DEN_PHY_READ_CTRL_REG_2_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_2_WIDTH  32                   
#define DEN_PHY_READ_CTRL_REG_3_ADDR   51  
#define DEN_PHY_READ_CTRL_REG_3_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_3_WIDTH  32                   
#define DEN_PHY_READ_CTRL_REG_4_ADDR   67  
#define DEN_PHY_READ_CTRL_REG_4_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_4_WIDTH  32                   
#define DEN_PHY_READ_CTRL_REG_5_ADDR   83  
#define DEN_PHY_READ_CTRL_REG_5_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_5_WIDTH  32                   
#define DEN_PHY_READ_CTRL_REG_6_ADDR   99  
#define DEN_PHY_READ_CTRL_REG_6_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_6_WIDTH  32                   
#define DEN_PHY_READ_CTRL_REG_7_ADDR   115 
#define DEN_PHY_READ_CTRL_REG_7_OFFSET 0                    
#define DEN_PHY_READ_CTRL_REG_7_WIDTH  32                   
#define PHY_DLL_MASTER_CTRL_REG_ADDR   4                    
#define PHY_DLL_MASTER_CTRL_REG_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_WIDTH  32                   
#define PHY_DLL_MASTER_CTRL_REG_0_ADDR 4   
#define PHY_DLL_MASTER_CTRL_REG_0_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_0_WIDTH 32                   
#define PHY_DLL_MASTER_CTRL_REG_1_ADDR 20  
#define PHY_DLL_MASTER_CTRL_REG_1_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_1_WIDTH 32                   
#define PHY_DLL_MASTER_CTRL_REG_2_ADDR 36  
#define PHY_DLL_MASTER_CTRL_REG_2_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_2_WIDTH 32                   
#define PHY_DLL_MASTER_CTRL_REG_3_ADDR 52  
#define PHY_DLL_MASTER_CTRL_REG_3_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_3_WIDTH 32                   
#define PHY_DLL_MASTER_CTRL_REG_4_ADDR 68  
#define PHY_DLL_MASTER_CTRL_REG_4_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_4_WIDTH 32                   
#define PHY_DLL_MASTER_CTRL_REG_5_ADDR 84  
#define PHY_DLL_MASTER_CTRL_REG_5_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_5_WIDTH 32                   
#define PHY_DLL_MASTER_CTRL_REG_6_ADDR 100 
#define PHY_DLL_MASTER_CTRL_REG_6_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_6_WIDTH 32                   
#define PHY_DLL_MASTER_CTRL_REG_7_ADDR 116 
#define PHY_DLL_MASTER_CTRL_REG_7_OFFSET 0                    
#define PHY_DLL_MASTER_CTRL_REG_7_WIDTH 32                   
#define PHY_DLL_OBS_REG_0_ADDR         7                    
#define PHY_DLL_OBS_REG_0_OFFSET       0                    
#define PHY_DLL_OBS_REG_0_WIDTH        32                   
#define PHY_DLL_OBS_REG_0_0_ADDR       7   
#define PHY_DLL_OBS_REG_0_0_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_0_WIDTH      32                   
#define PHY_DLL_OBS_REG_0_1_ADDR       23  
#define PHY_DLL_OBS_REG_0_1_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_1_WIDTH      32                   
#define PHY_DLL_OBS_REG_0_2_ADDR       39  
#define PHY_DLL_OBS_REG_0_2_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_2_WIDTH      32                   
#define PHY_DLL_OBS_REG_0_3_ADDR       55  
#define PHY_DLL_OBS_REG_0_3_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_3_WIDTH      32                   
#define PHY_DLL_OBS_REG_0_4_ADDR       71  
#define PHY_DLL_OBS_REG_0_4_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_4_WIDTH      32                   
#define PHY_DLL_OBS_REG_0_5_ADDR       87  
#define PHY_DLL_OBS_REG_0_5_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_5_WIDTH      32                   
#define PHY_DLL_OBS_REG_0_6_ADDR       103 
#define PHY_DLL_OBS_REG_0_6_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_6_WIDTH      32                   
#define PHY_DLL_OBS_REG_0_7_ADDR       119 
#define PHY_DLL_OBS_REG_0_7_OFFSET     0                    
#define PHY_DLL_OBS_REG_0_7_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_ADDR         8                    
#define PHY_DLL_OBS_REG_1_OFFSET       0                    
#define PHY_DLL_OBS_REG_1_WIDTH        32                   
#define PHY_DLL_OBS_REG_1_0_ADDR       8   
#define PHY_DLL_OBS_REG_1_0_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_0_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_1_ADDR       24  
#define PHY_DLL_OBS_REG_1_1_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_1_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_2_ADDR       40  
#define PHY_DLL_OBS_REG_1_2_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_2_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_3_ADDR       56  
#define PHY_DLL_OBS_REG_1_3_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_3_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_4_ADDR       72  
#define PHY_DLL_OBS_REG_1_4_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_4_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_5_ADDR       88  
#define PHY_DLL_OBS_REG_1_5_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_5_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_6_ADDR       104 
#define PHY_DLL_OBS_REG_1_6_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_6_WIDTH      32                   
#define PHY_DLL_OBS_REG_1_7_ADDR       120 
#define PHY_DLL_OBS_REG_1_7_OFFSET     0                    
#define PHY_DLL_OBS_REG_1_7_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_ADDR         9                    
#define PHY_DLL_OBS_REG_2_OFFSET       0                    
#define PHY_DLL_OBS_REG_2_WIDTH        32                   
#define PHY_DLL_OBS_REG_2_0_ADDR       9   
#define PHY_DLL_OBS_REG_2_0_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_0_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_1_ADDR       25  
#define PHY_DLL_OBS_REG_2_1_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_1_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_2_ADDR       41  
#define PHY_DLL_OBS_REG_2_2_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_2_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_3_ADDR       57  
#define PHY_DLL_OBS_REG_2_3_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_3_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_4_ADDR       73  
#define PHY_DLL_OBS_REG_2_4_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_4_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_5_ADDR       89  
#define PHY_DLL_OBS_REG_2_5_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_5_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_6_ADDR       105 
#define PHY_DLL_OBS_REG_2_6_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_6_WIDTH      32                   
#define PHY_DLL_OBS_REG_2_7_ADDR       121 
#define PHY_DLL_OBS_REG_2_7_OFFSET     0                    
#define PHY_DLL_OBS_REG_2_7_WIDTH      32                   
#define PHY_DLL_SLAVE_CTRL_REG_ADDR    5                    
#define PHY_DLL_SLAVE_CTRL_REG_OFFSET  0                    
#define PHY_DLL_SLAVE_CTRL_REG_WIDTH   32                   
#define PHY_DLL_SLAVE_CTRL_REG_0_ADDR  5   
#define PHY_DLL_SLAVE_CTRL_REG_0_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_0_WIDTH 8                   
#define PHY_DLL_SLAVE_CTRL_REG_1_ADDR  21  
#define PHY_DLL_SLAVE_CTRL_REG_1_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_1_WIDTH 8                   
#define PHY_DLL_SLAVE_CTRL_REG_2_ADDR  37  
#define PHY_DLL_SLAVE_CTRL_REG_2_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_2_WIDTH 8                   
#define PHY_DLL_SLAVE_CTRL_REG_3_ADDR  53  
#define PHY_DLL_SLAVE_CTRL_REG_3_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_3_WIDTH 8                   
#define PHY_DLL_SLAVE_CTRL_REG_4_ADDR  69  
#define PHY_DLL_SLAVE_CTRL_REG_4_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_4_WIDTH 8                   
#define PHY_DLL_SLAVE_CTRL_REG_5_ADDR  85  
#define PHY_DLL_SLAVE_CTRL_REG_5_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_5_WIDTH 8                   
#define PHY_DLL_SLAVE_CTRL_REG_6_ADDR  101 
#define PHY_DLL_SLAVE_CTRL_REG_6_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_6_WIDTH 8                   
#define PHY_DLL_SLAVE_CTRL_REG_7_ADDR  117 
#define PHY_DLL_SLAVE_CTRL_REG_7_OFFSET 8                    
#define PHY_DLL_SLAVE_CTRL_REG_7_WIDTH 8

#define read_ddr_reg(base, name, no) \
  (((*((volatile int *)base + name##_##no##_ADDR)) >> name##_##no##_OFFSET) & (-1ULL >> (32 - name##_##no##_WIDTH)))
#define read_ddr_reg_entire(base, name, no) \
  (*((volatile int *)base + name##_##no##_ADDR))
#define write_ddr_reg(base, name, no, val) \
  do { ((volatile int *)base)[name##_##no##_ADDR] = \
    (read_ddr_reg_entire(base, name, no) & ~((~(-1ULL << name##_##no##_WIDTH)) << name##_##no##_OFFSET)) | ((val) << name##_##no##_OFFSET); } while (0)
#define adjust_ddr_reg(ctrl_base, phy_base, no) \
  do { write_ddr_reg(phy_base, PHY_DLL_SLAVE_CTRL_REG, no, read_ddr_reg(phy_base, PHY_DLL_SLAVE_CTRL_REG, no) + read_ddr_reg(ctrl_base, WRLVL_DELAY, no)); } while (0)
#define adjust_ddr_regs(ctrl_base, phy_base) \
  do { adjust_ddr_reg(ctrl_base, phy_base, 0); \
adjust_ddr_reg(ctrl_base, phy_base, 1); \
adjust_ddr_reg(ctrl_base, phy_base, 2); \
adjust_ddr_reg(ctrl_base, phy_base, 3); \
adjust_ddr_reg(ctrl_base, phy_base, 4); \
adjust_ddr_reg(ctrl_base, phy_base, 5); \
adjust_ddr_reg(ctrl_base, phy_base, 6); \
adjust_ddr_reg(ctrl_base, phy_base, 7); } while (0)

#endif
