# -*- coding: utf-8 -*-
from PyQt4.QtGui import*
from PyQt4.QtCore import*

QTextCodec.setCodecForTr(QTextCodec.codecForName("utf8"))

class FloatDialog(QDialog):
    def __init__(self,parent=None):
	super(FloatDialog,self).__init__(parent)

	self.flag=-1 #-1 close , 0 open
	self.setMinimumWidth(220)
	self.setMinimumHeight(200)
	self.resize(230,200)
	self.setWindowFlags(Qt.WindowStaysOnTopHint)
	self.stages=QTableWidget()
	self.stages.setEditTriggers(QAbstractItemView.NoEditTriggers)
	self.stages.setSelectionBehavior(QAbstractItemView.SelectRows)
	self.stages.horizontalHeader().setStretchLastSection(True)	
	self.stages.horizontalHeader().setVisible(False)
	self.stages.verticalHeader().setVisible(False)
	self.stages.setShowGrid(False)
	self.stages.setColumnCount(2)
	self.stages.setRowCount(20)
	self.stages.verticalHeader().setDefaultSectionSize(25)
	self.stages.setColumnWidth(0,70)
	self.initDialog()
	stagesLay=QGridLayout()
	stagesLay.addWidget(self.stages,0,0)
	self.setLayout(stagesLay)
	
    def initDialog(self):
	self.stages.setItem(0,0,QTableWidgetItem(self.tr("stage0")))
	self.stages.setItem(0,1,QTableWidgetItem(self.tr("")))
	self.stages.item(0,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(1,0,QTableWidgetItem(self.tr("stage1")))
	self.stages.setItem(1,1,QTableWidgetItem(self.tr("")))
	self.stages.item(1,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(2,0,QTableWidgetItem(self.tr("stage2")))
	self.stages.setItem(2,1,QTableWidgetItem(self.tr("")))
	self.stages.item(2,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(3,0,QTableWidgetItem(self.tr("stage3")))
	self.stages.setItem(3,1,QTableWidgetItem(self.tr("")))
	self.stages.item(3,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(4,0,QTableWidgetItem(self.tr("stage4")))
	self.stages.setItem(4,1,QTableWidgetItem(self.tr("")))
	self.stages.item(4,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(5,0,QTableWidgetItem(self.tr("stage5")))
	self.stages.setItem(5,1,QTableWidgetItem(self.tr("")))
	self.stages.item(5,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(6,0,QTableWidgetItem(self.tr("stage6")))
	self.stages.setItem(6,1,QTableWidgetItem(self.tr("")))
	self.stages.item(6,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(7,0,QTableWidgetItem(self.tr("stage7")))
	self.stages.setItem(7,1,QTableWidgetItem(self.tr("")))
	self.stages.item(7,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(8,0,QTableWidgetItem(self.tr("stage8")))
	self.stages.setItem(8,1,QTableWidgetItem(self.tr("")))
	self.stages.item(8,0).setBackgroundColor(QColor(192,192,192))	
	self.stages.setItem(9,0,QTableWidgetItem(self.tr("stage9")))
	self.stages.setItem(9,1,QTableWidgetItem(self.tr("")))
	self.stages.item(9,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(10,0,QTableWidgetItem(self.tr("stage10")))
	self.stages.setItem(10,1,QTableWidgetItem(self.tr("")))
	self.stages.item(10,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(11,0,QTableWidgetItem(self.tr("stage11")))
	self.stages.setItem(11,1,QTableWidgetItem(self.tr("")))
	self.stages.item(11,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(12,0,QTableWidgetItem(self.tr("stage12")))
	self.stages.setItem(12,1,QTableWidgetItem(self.tr("")))
	self.stages.item(12,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(13,0,QTableWidgetItem(self.tr("stage13")))
	self.stages.setItem(13,1,QTableWidgetItem(self.tr("")))
	self.stages.item(13,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(14,0,QTableWidgetItem(self.tr("stage14")))
	self.stages.setItem(14,1,QTableWidgetItem(self.tr("")))
	self.stages.item(14,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(15,0,QTableWidgetItem(self.tr("stage15")))
	self.stages.setItem(15,1,QTableWidgetItem(self.tr("")))
	self.stages.item(15,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(16,0,QTableWidgetItem(self.tr("stage16")))
	self.stages.setItem(16,1,QTableWidgetItem(self.tr("")))
	self.stages.item(16,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(17,0,QTableWidgetItem(self.tr("stage17")))
	self.stages.setItem(17,1,QTableWidgetItem(self.tr("")))
	self.stages.item(17,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(18,0,QTableWidgetItem(self.tr("stage18")))
	self.stages.setItem(18,1,QTableWidgetItem(self.tr("")))
	self.stages.item(18,0).setBackgroundColor(QColor(192,192,192))
	self.stages.setItem(19,0,QTableWidgetItem(self.tr("stage19")))
	self.stages.setItem(19,1,QTableWidgetItem(self.tr("")))
	self.stages.item(19,0).setBackgroundColor(QColor(192,192,192))

    def closeEvent(self,event):
	self.flag=-1


