# -*- coding: utf-8 -*-
from PyQt4.QtGui import*
from PyQt4.QtCore import*

QTextCodec.setCodecForTr(QTextCodec.codecForName("utf8"))

class MPUViewWidget(QWidget):
    def __init__(self,parent=None):
	super(MPUViewWidget,self).__init__(parent)

	#define left Widget
	self.leftWidget=QWidget()
	self.BIU0LineBox=QGroupBox(self.tr("BIU0 Line"))
	self.BIU0LineBox.setMaximumHeight(90)
	self.BIU0LineBox.setMaximumWidth(100)
	self.BIU0Line=QListWidget()
	self.BIU0Line.setMaximumWidth(100)
	self.BIU0Line.addItem(self.tr("sn:41,sln:3"))
	self.BIU0Line.addItem(self.tr("sn:55,sln:4"))
	self.BIU0Line.addItem(self.tr("sn:69,sln:5"))
	BIU0LineLay=QVBoxLayout()
	BIU0LineLay.addWidget(self.BIU0Line)
	self.BIU0LineBox.setLayout(BIU0LineLay)

	self.DMButton=QPushButton(self.tr("DM"))
	self.DMButton.setFixedWidth(60)
	self.DMButton.setEnabled(False)

	self.BIU0Button=QPushButton(self.tr("BIU0"))
	self.BIU0Button.setFixedWidth(60)
	self.BIU1Button=QPushButton(self.tr("BIU1"))
	self.BIU1Button.setFixedWidth(60)
	self.BIU2Button=QPushButton(self.tr("BIU2"))
	self.BIU2Button.setFixedWidth(60)

	self.text=QLineEdit(self.tr("0xFFFF"))
	self.text.setFixedWidth(70)
	

	self.SHU0Button=QPushButton(self.tr("SHU0"))
	self.SHU0Button.setFixedWidth(60)
	self.MRFButton=QPushButton(self.tr("M RF"))
	self.MRFButton.setFixedWidth(60)
	self.SHU1Button=QPushButton(self.tr("SHU1"))
	self.SHU1Button.setFixedWidth(60)

	self.byteComboBox=QComboBox()
	self.byteComboBox.setFixedWidth(80)

	self.byteComboBox.insertItem(0,"8 Bytes")
	self.byteComboBox.insertItem(1,"7 Bytes")
	self.byteComboBox.insertItem(2,"6 Bytes")
	self.byteComboBox.insertItem(3,"5 Bytes")
	self.byteComboBox.insertItem(4,"4 Bytes")
	self.byteComboBox.insertItem(5,"3 Bytes")
	self.byteComboBox.insertItem(6,"2 Bytes")
	self.byteComboBox.insertItem(7,"1 Bytes")

	self.laneComboBox=QComboBox()
	self.laneComboBox.setFixedWidth(80)
	self.laneComboBox.insertItem(0,"Lane0")
	self.laneComboBox.insertItem(1,"Lane1")
	self.laneComboBox.insertItem(2,"Lane2")
	self.laneComboBox.insertItem(3,"Lane3")	
	self.IALUButton=QPushButton(self.tr("IALU"))
	self.IALUButton.setFixedWidth(60)
	self.IMACButton=QPushButton(self.tr("IMAC"))
	self.IMACButton.setFixedWidth(60)
	self.FALUButton=QPushButton(self.tr("FALU"))
	self.FALUButton.setFixedWidth(60)
	self.FMACButton=QPushButton(self.tr("FMAC"))
	self.FMACButton.setFixedWidth(60)
	#layout left Widget
	gridLay=QGridLayout()
	#gridLay.addWidget(self.BIU0LineBox,0,0,3,2)
	gridLay.addWidget(self.DMButton,5,0)
	gridLay.addWidget(self.BIU0Button,3,2)
	gridLay.addWidget(self.BIU1Button,5,2)
	gridLay.addWidget(self.BIU2Button,7,2)
	gridLay.addWidget(self.text,3,3)
	gridLay.addWidget(self.SHU0Button,1,4)
	gridLay.addWidget(self.MRFButton,5,4)
	gridLay.addWidget(self.SHU1Button,9,4)
	gridLay.addWidget(self.byteComboBox,0,5)
	gridLay.addWidget(self.laneComboBox,0,6)
	gridLay.addWidget(self.IALUButton,2,6)
	gridLay.addWidget(self.IMACButton,4,6)
	gridLay.addWidget(self.FALUButton,6,6)
	gridLay.addWidget(self.FMACButton,8,6)
	gridLay.setAlignment(Qt.AlignCenter)
	self.leftWidget.setLayout(gridLay)
	
	#define rightTab
	self.rightTab=QTabWidget()
	self.regFileWidget=QTableWidget()
	self.specialRegWidget=QTableWidget()
	self.traceWidget=QTableWidget()
	self.rightTab.addTab(self.regFileWidget,self.tr("Register File"))
	self.rightTab.addTab(self.specialRegWidget,self.tr("Special Register"))
	self.rightTab.addTab(self.traceWidget,self.tr("Trace"))
	#define regFileWidget
	self.regFileWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
	self.regFileWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
	self.regFileWidget.horizontalHeader().setVisible(False)
	self.regFileWidget.verticalHeader().setVisible(False)
	self.regFileWidget.setShowGrid(False)
	self.regFileWidget.setColumnCount(2)
	self.regFileWidget.setRowCount(69)
	self.regFileWidget.verticalHeader().setDefaultSectionSize(25)
	self.regFileWidget.setColumnWidth(0,122)
	#define regFileWidget M
	self.regFileWidget.setItem(0,0,QTableWidgetItem(self.tr("M")))
	self.regFileWidget.setItem(0,1,QTableWidgetItem(self.tr("")))
	self.regFileWidget.item(0,0).setBackgroundColor(QColor(192,192,192))
	self.regFileWidget.item(0,1).setBackgroundColor(QColor(192,192,192))
        self.regFileWidget.setItem(1,0,QTableWidgetItem(self.tr("M0")))
        self.regFileWidget.setItem(2,0,QTableWidgetItem(self.tr("M1")))
        self.regFileWidget.setItem(3,0,QTableWidgetItem(self.tr("M2")))
        self.regFileWidget.setItem(4,0,QTableWidgetItem(self.tr("M3")))
	self.regFileWidget.setItem(5,0,QTableWidgetItem(self.tr("M4")))
        self.regFileWidget.setItem(6,0,QTableWidgetItem(self.tr("M5")))
        self.regFileWidget.setItem(7,0,QTableWidgetItem(self.tr("M6")))
        self.regFileWidget.setItem(8,0,QTableWidgetItem(self.tr("M7")))
	self.regFileWidget.setItem(9,0,QTableWidgetItem(self.tr("M8")))
        self.regFileWidget.setItem(10,0,QTableWidgetItem(self.tr("M9")))
        self.regFileWidget.setItem(11,0,QTableWidgetItem(self.tr("M10")))
        self.regFileWidget.setItem(12,0,QTableWidgetItem(self.tr("M11")))
        self.regFileWidget.setItem(13,0,QTableWidgetItem(self.tr("M12")))
        self.regFileWidget.setItem(14,0,QTableWidgetItem(self.tr("M13")))
	self.regFileWidget.setItem(15,0,QTableWidgetItem(self.tr("M14")))
        self.regFileWidget.setItem(16,0,QTableWidgetItem(self.tr("M15")))
        self.regFileWidget.setItem(17,0,QTableWidgetItem(self.tr("M16")))
        self.regFileWidget.setItem(18,0,QTableWidgetItem(self.tr("M17")))
	self.regFileWidget.setItem(19,0,QTableWidgetItem(self.tr("M18")))
        self.regFileWidget.setItem(20,0,QTableWidgetItem(self.tr("M19")))
        self.regFileWidget.setItem(21,0,QTableWidgetItem(self.tr("M20")))
        self.regFileWidget.setItem(22,0,QTableWidgetItem(self.tr("M21")))
        self.regFileWidget.setItem(23,0,QTableWidgetItem(self.tr("M22")))
        self.regFileWidget.setItem(24,0,QTableWidgetItem(self.tr("M23")))
	self.regFileWidget.setItem(25,0,QTableWidgetItem(self.tr("M24")))
        self.regFileWidget.setItem(26,0,QTableWidgetItem(self.tr("M25")))
        self.regFileWidget.setItem(27,0,QTableWidgetItem(self.tr("M26")))
        self.regFileWidget.setItem(28,0,QTableWidgetItem(self.tr("M27")))
	self.regFileWidget.setItem(29,0,QTableWidgetItem(self.tr("M28")))
        self.regFileWidget.setItem(30,0,QTableWidgetItem(self.tr("M29")))
	self.regFileWidget.setItem(31,0,QTableWidgetItem(self.tr("M30")))
	self.regFileWidget.setItem(32,0,QTableWidgetItem(self.tr("M31")))
	#define regFileWidget SHU0 T
	self.regFileWidget.setItem(33,0,QTableWidgetItem(self.tr("SHU0 T")))
	self.regFileWidget.setItem(33,1,QTableWidgetItem(self.tr("")))
	self.regFileWidget.item(33,0).setBackgroundColor(QColor(192,192,192))
	self.regFileWidget.item(33,1).setBackgroundColor(QColor(192,192,192))
        self.regFileWidget.setItem(34,0,QTableWidgetItem(self.tr("T0")))
        self.regFileWidget.setItem(35,0,QTableWidgetItem(self.tr("T1")))
        self.regFileWidget.setItem(36,0,QTableWidgetItem(self.tr("T2")))
        self.regFileWidget.setItem(37,0,QTableWidgetItem(self.tr("T3")))
	self.regFileWidget.setItem(38,0,QTableWidgetItem(self.tr("T4")))
        self.regFileWidget.setItem(39,0,QTableWidgetItem(self.tr("T5")))
        self.regFileWidget.setItem(40,0,QTableWidgetItem(self.tr("T6")))
        self.regFileWidget.setItem(41,0,QTableWidgetItem(self.tr("T7")))
	self.regFileWidget.setItem(42,0,QTableWidgetItem(self.tr("T8")))
        self.regFileWidget.setItem(43,0,QTableWidgetItem(self.tr("T9")))
        self.regFileWidget.setItem(44,0,QTableWidgetItem(self.tr("T10")))
        self.regFileWidget.setItem(45,0,QTableWidgetItem(self.tr("T11")))
        self.regFileWidget.setItem(46,0,QTableWidgetItem(self.tr("T12")))
        self.regFileWidget.setItem(47,0,QTableWidgetItem(self.tr("T13")))
	self.regFileWidget.setItem(48,0,QTableWidgetItem(self.tr("T14")))
        self.regFileWidget.setItem(49,0,QTableWidgetItem(self.tr("T15")))
	self.regFileWidget.setItem(50,0,QTableWidgetItem(self.tr("T16")))
	#define regFileWidget SHU1 T
	self.regFileWidget.setItem(51,0,QTableWidgetItem(self.tr("SHU1 T")))
	self.regFileWidget.setItem(51,1,QTableWidgetItem(self.tr("")))
	self.regFileWidget.item(51,0).setBackgroundColor(QColor(192,192,192))
	self.regFileWidget.item(51,1).setBackgroundColor(QColor(192,192,192))
        self.regFileWidget.setItem(52,0,QTableWidgetItem(self.tr("T0")))
        self.regFileWidget.setItem(53,0,QTableWidgetItem(self.tr("T1")))
        self.regFileWidget.setItem(54,0,QTableWidgetItem(self.tr("T2")))
        self.regFileWidget.setItem(55,0,QTableWidgetItem(self.tr("T3")))
	self.regFileWidget.setItem(56,0,QTableWidgetItem(self.tr("T4")))
        self.regFileWidget.setItem(57,0,QTableWidgetItem(self.tr("T5")))
        self.regFileWidget.setItem(58,0,QTableWidgetItem(self.tr("T6")))
        self.regFileWidget.setItem(59,0,QTableWidgetItem(self.tr("T7")))
	self.regFileWidget.setItem(60,0,QTableWidgetItem(self.tr("T8")))
        self.regFileWidget.setItem(61,0,QTableWidgetItem(self.tr("T9")))
        self.regFileWidget.setItem(62,0,QTableWidgetItem(self.tr("T10")))
        self.regFileWidget.setItem(63,0,QTableWidgetItem(self.tr("T11")))
        self.regFileWidget.setItem(64,0,QTableWidgetItem(self.tr("T12")))
        self.regFileWidget.setItem(65,0,QTableWidgetItem(self.tr("T13")))
	self.regFileWidget.setItem(66,0,QTableWidgetItem(self.tr("T14")))
        self.regFileWidget.setItem(67,0,QTableWidgetItem(self.tr("T15")))
	self.regFileWidget.setItem(68,0,QTableWidgetItem(self.tr("T16")))

	mainLayout=QHBoxLayout()
	mainLayout.addWidget(self.leftWidget)
	mainLayout.addWidget(self.rightTab)
	mainLayout.setStretchFactor(self.leftWidget,2)
	mainLayout.setStretchFactor(self.rightTab,1)
	self.setLayout(mainLayout)







