# -*- coding: utf-8 -*-
from PyQt4.QtGui import*
from PyQt4.QtCore import*
from StageDialog import*

QTextCodec.setCodecForTr(QTextCodec.codecForName("utf8"))

class SPUViewWidget(QWidget):
    def __init__(self,parent=None):
	super(SPUViewWidget,self).__init__(parent)

	self.leftWidget=QWidget()
	self.stageButton=QPushButton("Instruction Pipeline Diagram")
	self.stageButton.setFixedSize(200,40)
	self.stageButton.setEnabled(False)
	self.connect(self.stageButton,SIGNAL("clicked()"),self.stageButtonSlot)
	leftLay=QVBoxLayout()
	leftLay.addWidget(self.stageButton)
	self.leftWidget.setLayout(leftLay)

	self.rightTab=QTabWidget()

	#define rightTab
	self.regFileWidget=QTableWidget()
	self.specialRegWidget=QTableWidget()
	self.traceWidget=QTableWidget()
	self.rightTab.addTab(self.regFileWidget,self.tr("Register File"))
	self.rightTab.addTab(self.specialRegWidget,self.tr("Special Register"))
	self.rightTab.addTab(self.traceWidget,self.tr("Trace"))
	self.regFileWidget.horizontalHeader().setStretchLastSection(True)
	self.specialRegWidget.horizontalHeader().setStretchLastSection(True)
	self.traceWidget.horizontalHeader().setStretchLastSection(True)

	#define regFileWidget
	self.regFileWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
	self.regFileWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
	self.regFileWidget.horizontalHeader().setVisible(False)
	self.regFileWidget.verticalHeader().setVisible(False)
	self.regFileWidget.setShowGrid(False)
	self.regFileWidget.setColumnCount(2)
	self.regFileWidget.setRowCount(66)
	self.regFileWidget.verticalHeader().setDefaultSectionSize(25)
	self.regFileWidget.setColumnWidth(0,122)

	#define regFileWidget R 
	self.regFileWidget.setItem(0,0,QTableWidgetItem(self.tr("R")))
	self.regFileWidget.setItem(0,1,QTableWidgetItem(self.tr("")))
	self.regFileWidget.item(0,0).setBackgroundColor(QColor(192,192,192))
	self.regFileWidget.item(0,1).setBackgroundColor(QColor(192,192,192))
        self.regFileWidget.setItem(1,0,QTableWidgetItem(self.tr("R0")))
	self.regFileWidget.setItem(1,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(2,0,QTableWidgetItem(self.tr("R1")))
	self.regFileWidget.setItem(2,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(3,0,QTableWidgetItem(self.tr("R2")))
	self.regFileWidget.setItem(3,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(4,0,QTableWidgetItem(self.tr("R3")))
	self.regFileWidget.setItem(4,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(5,0,QTableWidgetItem(self.tr("R4")))
	self.regFileWidget.setItem(5,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(6,0,QTableWidgetItem(self.tr("R5")))
	self.regFileWidget.setItem(6,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(7,0,QTableWidgetItem(self.tr("R6")))
	self.regFileWidget.setItem(7,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(8,0,QTableWidgetItem(self.tr("R7")))
	self.regFileWidget.setItem(8,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(9,0,QTableWidgetItem(self.tr("R8")))
	self.regFileWidget.setItem(9,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(10,0,QTableWidgetItem(self.tr("R9")))
	self.regFileWidget.setItem(10,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(11,0,QTableWidgetItem(self.tr("R10")))
	self.regFileWidget.setItem(11,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(12,0,QTableWidgetItem(self.tr("R11")))
	self.regFileWidget.setItem(12,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(13,0,QTableWidgetItem(self.tr("R12")))
	self.regFileWidget.setItem(13,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(14,0,QTableWidgetItem(self.tr("R13")))
	self.regFileWidget.setItem(14,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(15,0,QTableWidgetItem(self.tr("R14")))
	self.regFileWidget.setItem(15,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(16,0,QTableWidgetItem(self.tr("R15")))
	self.regFileWidget.setItem(16,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(17,0,QTableWidgetItem(self.tr("R16")))
	self.regFileWidget.setItem(17,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(18,0,QTableWidgetItem(self.tr("R17")))
	self.regFileWidget.setItem(18,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(19,0,QTableWidgetItem(self.tr("R18")))
	self.regFileWidget.setItem(19,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(20,0,QTableWidgetItem(self.tr("R19")))
	self.regFileWidget.setItem(20,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(21,0,QTableWidgetItem(self.tr("R20")))
	self.regFileWidget.setItem(21,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(22,0,QTableWidgetItem(self.tr("R21")))
	self.regFileWidget.setItem(22,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(23,0,QTableWidgetItem(self.tr("R22")))
	self.regFileWidget.setItem(23,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(24,0,QTableWidgetItem(self.tr("R23")))
	self.regFileWidget.setItem(24,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(25,0,QTableWidgetItem(self.tr("R24")))
	self.regFileWidget.setItem(25,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(26,0,QTableWidgetItem(self.tr("R25")))
	self.regFileWidget.setItem(26,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(27,0,QTableWidgetItem(self.tr("R26")))
	self.regFileWidget.setItem(27,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(28,0,QTableWidgetItem(self.tr("R27")))
	self.regFileWidget.setItem(28,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(29,0,QTableWidgetItem(self.tr("R28")))
	self.regFileWidget.setItem(29,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(30,0,QTableWidgetItem(self.tr("R29")))
	self.regFileWidget.setItem(30,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(31,0,QTableWidgetItem(self.tr("R30")))
	self.regFileWidget.setItem(31,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(32,0,QTableWidgetItem(self.tr("R31")))
	self.regFileWidget.setItem(32,1,QTableWidgetItem(self.tr("0")))
	#define regFileWidget J
	self.regFileWidget.setItem(33,0,QTableWidgetItem(self.tr("J")))
	self.regFileWidget.setItem(33,1,QTableWidgetItem(self.tr("")))
	self.regFileWidget.item(33,0).setBackgroundColor(QColor(192,192,192))
	self.regFileWidget.item(33,1).setBackgroundColor(QColor(192,192,192))
        self.regFileWidget.setItem(34,0,QTableWidgetItem(self.tr("J0")))
	self.regFileWidget.setItem(34,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(35,0,QTableWidgetItem(self.tr("J1")))
	self.regFileWidget.setItem(35,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(36,0,QTableWidgetItem(self.tr("J2")))
	self.regFileWidget.setItem(36,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(37,0,QTableWidgetItem(self.tr("J3")))
	self.regFileWidget.setItem(37,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(38,0,QTableWidgetItem(self.tr("J4")))
	self.regFileWidget.setItem(38,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(39,0,QTableWidgetItem(self.tr("J5")))
	self.regFileWidget.setItem(39,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(40,0,QTableWidgetItem(self.tr("J6")))
	self.regFileWidget.setItem(40,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(41,0,QTableWidgetItem(self.tr("J7")))
	self.regFileWidget.setItem(41,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(42,0,QTableWidgetItem(self.tr("J8")))
	self.regFileWidget.setItem(42,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(43,0,QTableWidgetItem(self.tr("J9")))
	self.regFileWidget.setItem(43,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(44,0,QTableWidgetItem(self.tr("J10")))
	self.regFileWidget.setItem(44,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(45,0,QTableWidgetItem(self.tr("J11")))
	self.regFileWidget.setItem(45,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(46,0,QTableWidgetItem(self.tr("J12")))
	self.regFileWidget.setItem(46,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(47,0,QTableWidgetItem(self.tr("J13")))
	self.regFileWidget.setItem(47,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(48,0,QTableWidgetItem(self.tr("J14")))
	self.regFileWidget.setItem(48,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(49,0,QTableWidgetItem(self.tr("J15")))
	self.regFileWidget.setItem(49,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(50,0,QTableWidgetItem(self.tr("J16")))
	self.regFileWidget.setItem(50,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(51,0,QTableWidgetItem(self.tr("J17")))
	self.regFileWidget.setItem(51,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(52,0,QTableWidgetItem(self.tr("J18")))
	self.regFileWidget.setItem(52,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(53,0,QTableWidgetItem(self.tr("J19")))
	self.regFileWidget.setItem(53,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(54,0,QTableWidgetItem(self.tr("J20")))
	self.regFileWidget.setItem(54,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(55,0,QTableWidgetItem(self.tr("J21")))
	self.regFileWidget.setItem(55,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(56,0,QTableWidgetItem(self.tr("J22")))
	self.regFileWidget.setItem(56,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(57,0,QTableWidgetItem(self.tr("J23")))
	self.regFileWidget.setItem(57,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(58,0,QTableWidgetItem(self.tr("J24")))
	self.regFileWidget.setItem(58,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(59,0,QTableWidgetItem(self.tr("J25")))
	self.regFileWidget.setItem(59,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(60,0,QTableWidgetItem(self.tr("J26")))
	self.regFileWidget.setItem(60,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(61,0,QTableWidgetItem(self.tr("J27")))
	self.regFileWidget.setItem(61,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(62,0,QTableWidgetItem(self.tr("J28")))
	self.regFileWidget.setItem(62,1,QTableWidgetItem(self.tr("0")))
        self.regFileWidget.setItem(63,0,QTableWidgetItem(self.tr("J29")))
	self.regFileWidget.setItem(63,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(64,0,QTableWidgetItem(self.tr("J30")))
	self.regFileWidget.setItem(64,1,QTableWidgetItem(self.tr("0")))
	self.regFileWidget.setItem(65,0,QTableWidgetItem(self.tr("J31")))
	self.regFileWidget.setItem(65,1,QTableWidgetItem(self.tr("0")))

	#define specialRegWidget
	self.specialRegWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
	self.specialRegWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
	self.specialRegWidget.horizontalHeader().setVisible(False)
	self.specialRegWidget.verticalHeader().setVisible(False)
	self.specialRegWidget.setShowGrid(False)
	self.specialRegWidget.setColumnCount(2)
	self.specialRegWidget.setRowCount(134)
	self.specialRegWidget.verticalHeader().setDefaultSectionSize(25)
	self.specialRegWidget.setColumnWidth(0,150)
	#define specialRegWidget 
	self.specialRegWidget.setItem(0,0,QTableWidgetItem(self.tr("Carry flag")))
	self.specialRegWidget.setItem(0,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(1,0,QTableWidgetItem(self.tr("Loop enable")))
	self.specialRegWidget.setItem(1,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(2,0,QTableWidgetItem(self.tr("Loop0 start")))
	self.specialRegWidget.setItem(2,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(3,0,QTableWidgetItem(self.tr("Loop0 end")))
	self.specialRegWidget.setItem(3,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(4,0,QTableWidgetItem(self.tr("Loop0 number")))
	self.specialRegWidget.setItem(4,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(5,0,QTableWidgetItem(self.tr("Loop1 start")))
	self.specialRegWidget.setItem(5,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(6,0,QTableWidgetItem(self.tr("Loop1 end")))
	self.specialRegWidget.setItem(6,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(7,0,QTableWidgetItem(self.tr("Loop1 number")))
	self.specialRegWidget.setItem(7,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(8,0,QTableWidgetItem(self.tr("MC.r0")))
	self.specialRegWidget.setItem(8,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(9,0,QTableWidgetItem(self.tr("MC.r1")))
	self.specialRegWidget.setItem(9,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(10,0,QTableWidgetItem(self.tr("MC.w0")))
	self.specialRegWidget.setItem(10,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(11,0,QTableWidgetItem(self.tr("MC.w1")))
	self.specialRegWidget.setItem(11,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(12,0,QTableWidgetItem(self.tr("MC.w2")))
	self.specialRegWidget.setItem(12,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(13,0,QTableWidgetItem(self.tr("MI.r0")))
	self.specialRegWidget.setItem(13,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(14,0,QTableWidgetItem(self.tr("MI.r1")))
	self.specialRegWidget.setItem(14,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(15,0,QTableWidgetItem(self.tr("MI.w0")))
	self.specialRegWidget.setItem(15,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(16,0,QTableWidgetItem(self.tr("MI.w1")))
	self.specialRegWidget.setItem(16,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(17,0,QTableWidgetItem(self.tr("MI.w2")))
	self.specialRegWidget.setItem(17,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(18,0,QTableWidgetItem(self.tr("MS.r0")))
	self.specialRegWidget.setItem(18,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(19,0,QTableWidgetItem(self.tr("MS.r1")))
	self.specialRegWidget.setItem(19,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(20,0,QTableWidgetItem(self.tr("MS.w0")))
	self.specialRegWidget.setItem(20,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(21,0,QTableWidgetItem(self.tr("MS.w1")))
	self.specialRegWidget.setItem(21,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(22,0,QTableWidgetItem(self.tr("MS.w2")))
	self.specialRegWidget.setItem(22,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(23,0,QTableWidgetItem(self.tr("KB0")))
	self.specialRegWidget.setItem(23,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(24,0,QTableWidgetItem(self.tr("KB1")))
	self.specialRegWidget.setItem(24,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(25,0,QTableWidgetItem(self.tr("KB2")))
	self.specialRegWidget.setItem(25,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(26,0,QTableWidgetItem(self.tr("KB3")))
	self.specialRegWidget.setItem(26,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(27,0,QTableWidgetItem(self.tr("KB4")))
	self.specialRegWidget.setItem(27,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(28,0,QTableWidgetItem(self.tr("KB5")))
	self.specialRegWidget.setItem(28,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(29,0,QTableWidgetItem(self.tr("KB6")))
	self.specialRegWidget.setItem(29,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(30,0,QTableWidgetItem(self.tr("KB7")))
	self.specialRegWidget.setItem(30,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(31,0,QTableWidgetItem(self.tr("KB8")))
	self.specialRegWidget.setItem(31,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(32,0,QTableWidgetItem(self.tr("KB9")))
	self.specialRegWidget.setItem(32,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(33,0,QTableWidgetItem(self.tr("KB10")))
	self.specialRegWidget.setItem(33,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(34,0,QTableWidgetItem(self.tr("KB11")))
	self.specialRegWidget.setItem(34,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(35,0,QTableWidgetItem(self.tr("KB12")))
	self.specialRegWidget.setItem(35,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(36,0,QTableWidgetItem(self.tr("KB13")))
	self.specialRegWidget.setItem(36,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(37,0,QTableWidgetItem(self.tr("KB14")))
	self.specialRegWidget.setItem(37,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(38,0,QTableWidgetItem(self.tr("KB15")))
	self.specialRegWidget.setItem(38,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(39,0,QTableWidgetItem(self.tr("KE0")))
	self.specialRegWidget.setItem(39,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(40,0,QTableWidgetItem(self.tr("KE1")))
	self.specialRegWidget.setItem(40,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(41,0,QTableWidgetItem(self.tr("KE2")))
	self.specialRegWidget.setItem(41,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(42,0,QTableWidgetItem(self.tr("KE3")))
	self.specialRegWidget.setItem(42,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(43,0,QTableWidgetItem(self.tr("KE4")))
	self.specialRegWidget.setItem(43,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(44,0,QTableWidgetItem(self.tr("KE5")))
	self.specialRegWidget.setItem(44,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(45,0,QTableWidgetItem(self.tr("KE6")))
	self.specialRegWidget.setItem(45,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(46,0,QTableWidgetItem(self.tr("KE7")))
	self.specialRegWidget.setItem(46,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(47,0,QTableWidgetItem(self.tr("KE8")))
	self.specialRegWidget.setItem(47,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(48,0,QTableWidgetItem(self.tr("KE9")))
	self.specialRegWidget.setItem(48,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(49,0,QTableWidgetItem(self.tr("KE10")))
	self.specialRegWidget.setItem(49,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(50,0,QTableWidgetItem(self.tr("KE11")))
	self.specialRegWidget.setItem(50,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(51,0,QTableWidgetItem(self.tr("KE12")))
	self.specialRegWidget.setItem(51,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(52,0,QTableWidgetItem(self.tr("KE13")))
	self.specialRegWidget.setItem(52,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(53,0,QTableWidgetItem(self.tr("KE14")))
	self.specialRegWidget.setItem(53,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(54,0,QTableWidgetItem(self.tr("KE15")))
	self.specialRegWidget.setItem(54,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(55,0,QTableWidgetItem(self.tr("KS0")))
	self.specialRegWidget.setItem(55,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(56,0,QTableWidgetItem(self.tr("KS1")))
	self.specialRegWidget.setItem(56,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(57,0,QTableWidgetItem(self.tr("KS2")))
	self.specialRegWidget.setItem(57,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(58,0,QTableWidgetItem(self.tr("KS3")))
	self.specialRegWidget.setItem(58,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(59,0,QTableWidgetItem(self.tr("KS4")))
	self.specialRegWidget.setItem(59,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(60,0,QTableWidgetItem(self.tr("KS5")))
	self.specialRegWidget.setItem(60,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(61,0,QTableWidgetItem(self.tr("KS6")))
	self.specialRegWidget.setItem(61,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(62,0,QTableWidgetItem(self.tr("KS7")))
	self.specialRegWidget.setItem(62,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(63,0,QTableWidgetItem(self.tr("KS8")))
	self.specialRegWidget.setItem(63,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(64,0,QTableWidgetItem(self.tr("KS9")))
	self.specialRegWidget.setItem(64,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(65,0,QTableWidgetItem(self.tr("KS10")))
	self.specialRegWidget.setItem(65,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(66,0,QTableWidgetItem(self.tr("KS11")))
	self.specialRegWidget.setItem(66,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(67,0,QTableWidgetItem(self.tr("KS12")))
	self.specialRegWidget.setItem(67,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(68,0,QTableWidgetItem(self.tr("KS13")))
	self.specialRegWidget.setItem(68,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(69,0,QTableWidgetItem(self.tr("KS14")))
	self.specialRegWidget.setItem(69,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(70,0,QTableWidgetItem(self.tr("KS15")))
	self.specialRegWidget.setItem(70,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(71,0,QTableWidgetItem(self.tr("KI0")))
	self.specialRegWidget.setItem(71,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(72,0,QTableWidgetItem(self.tr("KI1")))
	self.specialRegWidget.setItem(72,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(73,0,QTableWidgetItem(self.tr("KI2")))
	self.specialRegWidget.setItem(73,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(74,0,QTableWidgetItem(self.tr("KI3")))
	self.specialRegWidget.setItem(74,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(75,0,QTableWidgetItem(self.tr("KI4")))
	self.specialRegWidget.setItem(75,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(76,0,QTableWidgetItem(self.tr("KI5")))
	self.specialRegWidget.setItem(76,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(77,0,QTableWidgetItem(self.tr("KI6")))
	self.specialRegWidget.setItem(77,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(78,0,QTableWidgetItem(self.tr("KI7")))
	self.specialRegWidget.setItem(78,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(79,0,QTableWidgetItem(self.tr("KI8")))
	self.specialRegWidget.setItem(79,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(80,0,QTableWidgetItem(self.tr("KI9")))
	self.specialRegWidget.setItem(80,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(81,0,QTableWidgetItem(self.tr("KI10")))
	self.specialRegWidget.setItem(81,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(82,0,QTableWidgetItem(self.tr("KI11")))
	self.specialRegWidget.setItem(82,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(83,0,QTableWidgetItem(self.tr("KI12")))
	self.specialRegWidget.setItem(83,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(84,0,QTableWidgetItem(self.tr("KI13")))
	self.specialRegWidget.setItem(84,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(85,0,QTableWidgetItem(self.tr("KI14")))
	self.specialRegWidget.setItem(85,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(86,0,QTableWidgetItem(self.tr("KI15")))
	self.specialRegWidget.setItem(86,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(87,0,QTableWidgetItem(self.tr("KM0L0")))
	self.specialRegWidget.setItem(87,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(88,0,QTableWidgetItem(self.tr("KM0L1")))
	self.specialRegWidget.setItem(88,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(89,0,QTableWidgetItem(self.tr("KM0H0")))
	self.specialRegWidget.setItem(89,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(90,0,QTableWidgetItem(self.tr("KM0H1")))
	self.specialRegWidget.setItem(90,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(91,0,QTableWidgetItem(self.tr("KM1L0")))
	self.specialRegWidget.setItem(91,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(92,0,QTableWidgetItem(self.tr("KM1L1")))
	self.specialRegWidget.setItem(92,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(93,0,QTableWidgetItem(self.tr("KM1H0")))
	self.specialRegWidget.setItem(93,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(94,0,QTableWidgetItem(self.tr("KM1H1")))
	self.specialRegWidget.setItem(94,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(95,0,QTableWidgetItem(self.tr("KM2L0")))
	self.specialRegWidget.setItem(95,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(96,0,QTableWidgetItem(self.tr("KM2L1")))
	self.specialRegWidget.setItem(96,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(97,0,QTableWidgetItem(self.tr("KM2H0")))
	self.specialRegWidget.setItem(97,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(98,0,QTableWidgetItem(self.tr("KM2H1")))
	self.specialRegWidget.setItem(98,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(99,0,QTableWidgetItem(self.tr("KG0")))
	self.specialRegWidget.setItem(99,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(100,0,QTableWidgetItem(self.tr("KG1")))
	self.specialRegWidget.setItem(100,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(101,0,QTableWidgetItem(self.tr("KG2")))
	self.specialRegWidget.setItem(101,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(102,0,QTableWidgetItem(self.tr("KL0")))
	self.specialRegWidget.setItem(102,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(103,0,QTableWidgetItem(self.tr("KL1")))
	self.specialRegWidget.setItem(103,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(104,0,QTableWidgetItem(self.tr("KL2")))
	self.specialRegWidget.setItem(104,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(105,0,QTableWidgetItem(self.tr("KL3")))
	self.specialRegWidget.setItem(105,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(106,0,QTableWidgetItem(self.tr("KL4")))
	self.specialRegWidget.setItem(106,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(107,0,QTableWidgetItem(self.tr("KL5")))
	self.specialRegWidget.setItem(107,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(108,0,QTableWidgetItem(self.tr("KL6")))
	self.specialRegWidget.setItem(108,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(109,0,QTableWidgetItem(self.tr("KL7")))
	self.specialRegWidget.setItem(109,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(110,0,QTableWidgetItem(self.tr("KL8")))
	self.specialRegWidget.setItem(110,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(111,0,QTableWidgetItem(self.tr("KL9")))
	self.specialRegWidget.setItem(111,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(112,0,QTableWidgetItem(self.tr("KL10")))
	self.specialRegWidget.setItem(112,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(113,0,QTableWidgetItem(self.tr("KL11")))
	self.specialRegWidget.setItem(113,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(114,0,QTableWidgetItem(self.tr("KL12")))
	self.specialRegWidget.setItem(114,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(115,0,QTableWidgetItem(self.tr("KL13")))
	self.specialRegWidget.setItem(115,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(116,0,QTableWidgetItem(self.tr("KL14")))
	self.specialRegWidget.setItem(116,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(117,0,QTableWidgetItem(self.tr("KL15")))
	self.specialRegWidget.setItem(117,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(118,0,QTableWidgetItem(self.tr("KC0")))
	self.specialRegWidget.setItem(118,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(119,0,QTableWidgetItem(self.tr("KC1")))
	self.specialRegWidget.setItem(119,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(120,0,QTableWidgetItem(self.tr("KC2")))
	self.specialRegWidget.setItem(120,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(121,0,QTableWidgetItem(self.tr("KC3")))
	self.specialRegWidget.setItem(121,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(122,0,QTableWidgetItem(self.tr("KC4")))
	self.specialRegWidget.setItem(122,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(123,0,QTableWidgetItem(self.tr("KC5")))
	self.specialRegWidget.setItem(123,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(124,0,QTableWidgetItem(self.tr("KC6")))
	self.specialRegWidget.setItem(124,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(125,0,QTableWidgetItem(self.tr("KC7")))
	self.specialRegWidget.setItem(125,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(126,0,QTableWidgetItem(self.tr("KC8")))
	self.specialRegWidget.setItem(126,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(127,0,QTableWidgetItem(self.tr("KC9")))
	self.specialRegWidget.setItem(127,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(128,0,QTableWidgetItem(self.tr("KC10")))
	self.specialRegWidget.setItem(128,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(129,0,QTableWidgetItem(self.tr("KC11")))
	self.specialRegWidget.setItem(129,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(130,0,QTableWidgetItem(self.tr("KC12")))
	self.specialRegWidget.setItem(130,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(131,0,QTableWidgetItem(self.tr("KC13")))
	self.specialRegWidget.setItem(131,1,QTableWidgetItem(self.tr("0")))
	self.specialRegWidget.setItem(132,0,QTableWidgetItem(self.tr("KC14")))
	self.specialRegWidget.setItem(132,1,QTableWidgetItem(self.tr("0")))
        self.specialRegWidget.setItem(133,0,QTableWidgetItem(self.tr("KC15")))
	self.specialRegWidget.setItem(133,1,QTableWidgetItem(self.tr("0")))

	mainLayout=QHBoxLayout()
	mainLayout.addWidget(self.leftWidget)
	mainLayout.addWidget(self.rightTab)
	mainLayout.setStretchFactor(self.leftWidget,5)
	mainLayout.setStretchFactor(self.rightTab,2)
	self.setLayout(mainLayout)

	self.stageDialog=StageDialog()

    def stageButtonSlot(self):
	self.stageDialog.setWindowTitle("SPU Instruction Pipeline Diagram")
	self.stageDialog.show()

    def updateSPUWidget(self,r):
	for i in range (0,64):
	    if i>=0 and i<=31:
	        if r[188+i]!="nop":
		    self.regFileWidget.item(i+1,1).setData(0,r[188+i])
		    self.regFileWidget.item(i+1,1).setToolTip(r[188+i])
		else:
		    self.regFileWidget.item(i+1,1).setData(0,"0")
		    self.regFileWidget.item(i+1,1).setToolTip("")
	        self.regFileWidget.item(i+1,1).setTextColor(QColor(0,0,0))
	    else:
	        if r[188+i]!="nop":
		    self.regFileWidget.item(i+2,1).setData(0,r[188+i])
		    self.regFileWidget.item(i+2,1).setToolTip(r[188+i])
		else:
		    self.regFileWidget.item(i+2,1).setData(0,"0")
		    self.regFileWidget.item(i+2,1).setToolTip("")
	        self.regFileWidget.item(i+2,1).setTextColor(QColor(0,0,0))

    def updateSPURegWFlag(self,r):
	i=r[7]
	if r[6]=="R Reg":
	    self.regFileWidget.item(i+1,1).setTextColor(QColor(255,0,0))
	elif r[6]=="J Reg":
	    self.regFileWidget.item(i+34,1).setTextColor(QColor(255,0,0))

    def updateSPURegRRFlag(self,i):
	if self.regFileWidget.item(i+1,1).textColor()==QColor(255,0,0):
	    self.regFileWidget.item(i+1,1).setTextColor(QColor(255,153,18))

    def updateSPURegRJFlag(self,i):
	if self.regFileWidget.item(i+34,1).textColor()==QColor(255,0,0):
	    self.regFileWidget.item(i+34,1).setTextColor(QColor(255,153,18))



